### ISSUE TITLE
Svelte 5 support

### ISSUE THREAD

**Issue by jpx40** [threlte/threlte#1020]
Hey,
do plan to move the Library to Svelte 5 soon?

**Comment by michealparks** [comment]
See this issue: https://github.com/threlte/threlte/issues/973

**Comment by jpx40** [comment]
> See this issue: #973
> 
> You can use the `next` release now. We'll likely promote the next branch to Threlte 8 soon after Svelte 5 is ready. We won't migrate any of Threlte's hooks to runes for now to allow people to slowly migrate.

oh thanks, i use svelte 5 currently this will make it easier

**Comment by jpx40** [comment]
> See this issue: #973
> 
> You can use the `next` release now. We'll likely promote the next branch to Threlte 8 soon after Svelte 5 is ready. We won't migrate any of Threlte's hooks to runes for now to allow people to slowly migrate. 


You migth need runes since the system don't really works with out them anymore.
