### ISSUE TITLE
Migrate `<Gizmo>`'s internals to use `<HUD>`

### ISSUE THREAD

**Issue by michealparks** [threlte/threlte#1023]
This should fix click issues that users are experiencing, because with HUD we can simply just raycast from the viewport instead of creating weird invisible DOM elements.

**Comment by DefinitelyMaybe** [comment]
closing for now. We have a [new gizmo](https://next.threlte.xyz/docs/reference/extras/gizmo) since #1254 was merged 🎉 

happy for the issue to be reopen by OP if needed
