### ISSUE TITLE
Search doesn't show < and > correctly 

### ISSUE THREAD

**Issue by flo-bit** [threlte/threlte#1024]
Search command palette on documentation website shows html tags instead of < and >

See: 
<img width="870" alt="threlte" src="https://github.com/threlte/threlte/assets/45694132/db8b38eb-9083-4100-91fa-153aaa31275d">

**Comment by DefinitelyMaybe** [comment]
Yes. Also `ask AI` doesn't work anymore either.

**Comment by joshwashywash** [comment]
closed with #1297
