### ISSUE TITLE
[next] eliminate cleanup function in `oncreate` prop in favor of returning optional cleanup function

### ISSUE THREAD

**Issue by joshwashywash** [threlte/threlte#1088]
currently to run a function on cleanup you do something like this

```svelte
<T.Mesh
  oncreate={({ref, cleanup}) => {
    cleanup(() => {
      console.log(ref);
    });
  }}
>
  <T.BoxGeometry />
</T.Mesh>
```

i think `oncreate` should return an optional cleanup function similar to svelte 5's `$effect`. `$effect` runs an optional cleanup function when a component is destroyed (and before the effect runs again)

```svelte
<script>
  $effect(() => {
    return () => {
      console.log('goodbye');
    }
  });
</script>
```

`oncreate` could mimic this behavior. something like this:

```svelte
<T.Mesh
  oncreate={(ref) => {
    return () => {
      console.log(ref);
    }
  }}
>
<T.BoxGeometry />
</T.Mesh>
```

this isn't exactly the same as `$effect` because it won't run reactively (and it shouldn't) but i think it's a little simpler overall.

i took a look at the [implementation](https://github.com/threlte/threlte/blob/next/packages/core/src/lib/components/T/utils/useCreateEvent.ts)

it looks like you could do something like this in `dispatchCreateEvent`:

```typescript
const dispatchCreateEvent = () => {
  // ...
  const cleanup = oncreate?.(ref);
  if (cleanup !== undefined) {
    cleanupFunctions.push(cleanup);
  }
  // ...
}
```

but i'm not entirely sure it's that simple.

if this change did occur, it would have to be added to the migration guide and could cause some friction when people upgrade to the latest version of threlte. they've already got to replace `on:create` with `oncreate` unless there will be a migration script to help with that.

**Comment by grischaerbe** [comment]
This API design was a limitation of the old Svelte event system and your design approach is indeed preferable. Do you want to make a PR for that? If you need help, feel free to hit me up [on Discord](http://chat.threlte.xyz)!

**Comment by joshwashywash** [comment]
alright sounds like a plan. i'll try to create a pr later today for it and i'll hit you up on discord for any questions. thanks @grischaerbe 😎
