### ISSUE TITLE
Nice to have: Gizmo props for custom labels 

### ISSUE THREAD

**Issue by spikespiegel91** [threlte/threlte#1089]
Hello! 
It would be nice to be able to change the Gizmo default axis label text (X, Y , Z) with a custom user label. This would be useful in case you want to show "N" and "E" in the Gizmo (North, East) for geographic applications. 

Currently the axis labels are hardcoded text ('X', 'Y', 'Z') but adding yLabel?: string  to GizmoProps in Gizmo.d.ts and setting the props in Gizmo.svelte doesn't take much and would male this possible.

Here is an example of using a custom label in the Y axis: 
![image](https://github.com/user-attachments/assets/2864735c-d670-411c-ba0a-1d6d7dfa46fd)

![image](https://github.com/user-attachments/assets/b0b52b1f-9129-4b18-bc3e-83d782b7e297)

**Comment by DefinitelyMaybe** [comment]
Hey! That's an easy as idea for the Gizmo component. I'm sure some folks might like to adjust their labelling to like X -> Y or Z -> Y. If compass directions work for you then you do you 😄
