### ISSUE TITLE
[@threlte/extras 9.0.0-next.22] No DRACOLoader instance provided in new 

### ISSUE THREAD

**Issue by Omicrxn** [threlte/threlte#1092]
Hi after using the gltf package on the next version I found out that my 3d gltf model gives this error:
`"THREE.GLTFLoader: No DRACOLoader instance provided."`

Also with a freshly exported gltf, without Draco comprensión, it doesn't give the error but It doesn't show anything. I can't say if the problem relies on @threlte/gltf or in the extras package

**Comment by DefinitelyMaybe** [comment]
Double check it's not the changes we made. [Next Migration Guide](https://next.threlte.xyz/docs/learn/advanced/migration-guides#usegltf-and-gltf)

We made some changes for better tree-shaking
