### ISSUE TITLE
[next] using non-default camera causes `camera` currentWritable to update on any `size` store changes

### ISSUE THREAD

**Issue by joshwashywash** [threlte/threlte#1122]
## to reproduce

create a scene that uses a different camera than the default one that threlte context provides and log out the camera store with `$inspect`.

```svelte
<script>
  import { T, useThrelte } from '@threlte/core';

  const { camera } = useThrelte();

  $inspect($camera);
</script>

<T.PerspectiveCamera makeDefault />
```

resize the window so that the canvas size changes. the size is tracked in the `size` store from the threlte context.

the camera gets updated and logged to the console each time `size` updates. this doesn't happen if you use the default camera provided by the context

```diff
<script>
  import { T, useThrelte } from '@threlte/core';

  const { camera } = useThrelte();

  $inspect($camera);
</script>

- <T.PerspectiveCamera makeDefault />
```

## possible cause:

i think i tracked it down to this:

https://github.com/threlte/threlte/blob/92c1293f8d7c77bce0dce0a431cfe13c25c2df2a/packages/core/src/lib/components/T/utils/useCamera.ts#L27-L48

which watches `size` to adjust the camera's properties but also calls `camera.set(ref)` anytime `size` updates which is not necessary if all that needs to be done is updating the camera's properties.

https://github.com/threlte/threlte/blob/92c1293f8d7c77bce0dce0a431cfe13c25c2df2a/packages/core/src/lib/components/T/utils/useCamera.ts#L29-L32

the code above is skipped if the default camera is in use or rather if `makeDefault` is false.

## solution?

i'm thinking changes to `makeDefault` can be done in a separate watch function and that will but a reference to the camera is still needed in the callback function.

a quick solution might be to only set the camera store if `camera.current` !== `ref`

```diff
watch([currentRef, manual, makeDefault, size], ([ref, manual, makeDefault, size]) => {
  if (!ref) return
  if (makeDefault) {
+   if (camera.current !== ref) {
      camera.set(ref)
+   }
    invalidate()
  }
  // rest of watch
})
```

**Comment by grischaerbe** [comment]
Fixed in #1125.
Thanks a lot, great catch!
