### ISSUE TITLE
<TransformControls> broken due to three.js r169 changes

### ISSUE THREAD

**Issue by edsunman** [threlte/threlte#1157]
As of three.js version r169 TransformControls are derived from Controls and require a new getHelper() method to add to the scene.

https://github.com/mrdoob/three.js/pull/29146
https://github.com/mrdoob/three.js/wiki/Migration-Guide#r169--r170

I had a go at trying to fix this in the <TransformControls> component but I got a lot of dispose errors from the core package that I didn't understand so I gave up 😂

Also r169 broke the dispose() method in TransformControls but r170 fixed it:

https://github.com/mrdoob/three.js/pull/29512

**Comment by grischaerbe** [comment]
Done in #1176 :)
