### ISSUE TITLE
[next] update custom-abstraction.mdx to match new `types.ts` documentation/abstraction style

### ISSUE THREAD

**Issue by joshwashywash** [threlte/threlte#1167]
update this page: https://next.threlte.xyz/docs/learn/advanced/custom-abstractions

I don't know if we want people to think they have to use a `types.ts` file instead of typing things in the component. I think it's a good practice to separate types from the code that actually runs but it's not necessary in a general case.

I also think it might be a good idea to include information about doing something like this:

```typescript
type WhateverComponentProps = Props<Group> & {
  // a more concrete example of putting props in here
}
```

and maybe add info about the second type argument to `Props` in cases where they want to pass more than just the ref through the children snippet.

Maybe we can use this file as an example of a custom component: https://github.com/threlte/threlte/blob/next/apps/docs/src/examples/extras/bake-shadows/spaceships/Spaceship.svelte

it doesn't showcase using the "Snippet" argument of Props though but maybe it can be used as a guide.

see #1161 for more details.

**Comment by grischaerbe** [comment]
Done!
