### ISSUE TITLE
[next] DisposableProps type considerations/proposal

### ISSUE THREAD

**Issue by joshwashywash** [threlte/threlte#1170]
`dispose` is exposed by every T component. even components that can't be disposed have autocompletion for `dispose`

```svelte
<T.Color />
<!--    ^ autocompletes for `dispose` -->
```

currently `DisposableProps` is [this](https://github.com/threlte/threlte/blob/f47e3e9b16530aae55daedb5bd194a5d27dc437a/packages/core/src/lib/components/T/types.ts#L72-L77)

i wonder if this could be fixed with a type like this

```typescript
type DisposeProps<Type> = Type extends {dispose: () => void} : { dispose?: boolean } : {}
```

we're &ing the type in `Props` so i think `{}` is okay to use since `Type & {} === Type`, at least for objects.

I changed the name to `DisposeProps` cuz `DisposableProps` might mean that the props inside it are disposable. That's a nitpick though. It looks like `DisposableProps` is only used in the `T/types.ts` file so it might even be possible to inline the type if that's preferred.

```typescript
type Props<Type> = {
  Type extends {dispose: () => void} : { dispose?: boolean } : {} &
  // everything else
}
```

The type that you get in the editor for `Props` is pretty opaque but if we convert to less opaque types, i don't know if that will be anymore useful. Inlining above just gets rid of the `DisposableProps` name.

**Comment by grischaerbe** [comment]
Fixed in #1182 🎉 

I wasn't able to get rid of autocompletion, but it's an error if you use anything meaningful. That is because leaving it out of the type (`{}`) still includes it in the `AnyProps` type. That's why they need to be `{ dispose?: never }`. They autocomplete, but will error if you e.g. `<T.Mesh dispose={false} />` 👍
