### ISSUE TITLE
[next] lava lamp example types aren't good

### ISSUE THREAD

**Issue by joshwashywash** [threlte/threlte#1194]
I was a little sloppy with the lava lamp example types. `MarchingCube.svelte`, `MarchingPlane.svelte`, and `MarchingCubes.svelte` all have type errors in them.

Not sure if we wanna throw this in with `types.ts` refactoring kinda like #1163. I'll take a crack at it tomorrow.

**Comment by DefinitelyMaybe** [comment]
There are a large amount of type/lint errors that `astro check` picks up in my docs remake using starlight. Definitely worth putting in some effort to up the standard 👍

**Comment by joshwashywash** [comment]
closed with #1196
