### ISSUE TITLE
Advanced control over the actual render call

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#122]
Right now the frameloop calls `ctx.renderer.render(ctx.scene, camera)` and there's no way to intercept or hook onto that.

I guess a property in the renderContext would be great. Something like

```ts
const { useRender } = useThrelteRender()

// first argument is the con
useRender(({ renderer, camera, scene }) => {
  renderer.render(get(camera), scene)
})
```

`react-three-fiber` solves this with positive and negative indices on the respective property `order` of the `useFrame` hook. I'm not a huge fan of that as it's somewhat misleading and I like to think in "0 and up" to prioritize and convert that to "up to 0" is a bit of a stretch on the fly. Also computationally a bit more expensive. Also, and I think this is the huge difference: **Compared to `useFrame`, this hook would only be called in the event of an invalidated frame**.

I'm still undecided and I think the whole `useFrame` and `invalidate` pattern needs a bit of an overhaul.

**Comment by jerzakm** [comment]
I'd love to help progress this, as much as I am able to. Here are a few of my quick thoughts, I'll add more on later after I hear feedback and get more familiar with threlte/three internals.

Here's an approach I thought of:
1.  `<Canvas/>` is a component made of a few others with default configs. If user wanted to then use a custom canvas, context or rneder loop, they would provide their own components and config.

Quick mockup - 

```html
// This is default <Canvas/> provided by threlte

<script>
   import defaultRenderLoop from 'x/internals'
   
   const renderLoop = defaultRenderLoop()
   const webGlConfig = {...}
   const others = ... otherDefaultProps

   let canvas
   let ctx // webglcontext from above canvas
</script>

<canvas bind:canvas/>

<Renderer {renderLoop} {webGLConfig} {others} {canvas} {ctx}>
   <slot/>
</Renderer>
```

Then, if someone

```html
// <UsersCustomCanvas/> made by user

<script>
   	
   const registeredUseFrames = []  // fetch the store where 

   const renderLoop = defaultRenderLoop()
   const webGlConfig = {...}
   const others = ... otherDefaultProps


   export  let ctx // user is passing only WebGL context here, no canvas. 
   
   const renderLoop = () => {
       // user Logic, like
      renderer.setRenderTarget(rt1)
      // way that user can manually hande stuff from useFrame in components
      for (const f of registeredUseFrames){
      //do it
         f()
      }
      renderer.setRenderTarget(rt2)
      doAnotherThing()
	  renderer.setRenderTarget(null)
}


}
</script>

<canvas bind:canvas/>

<Renderer {renderLoop} {webGLConfig} {others} {canvas} {ctx}>
  <slot/>
</Renderer>
```

Let me know if it's dumb or doesn't make sense. I quickly scribbled it on here so it's a bit chaotic :)

**Comment by jerzakm** [comment]
An update on my previous ramblings. Same but different, this time I propose we consider building <Canvas/> only out of composable Plugins. Default Canvas would have the same functionality as it does now, and custom solutions should be relatively easy to roll out and reason with.

```html

<!-- This is roughly how I'd see a default Canvas structured
   It'd be made out of multiple plugins to re-create 
   the functionality that a <Canvas/> has now, but more 
   advanced user can pick and choose what they want and 
   roll in their own solutions
  -->

<canvas
  bind:this={canvas}
  {doDefaultCanvasStuff}
  use:parentSizeAction
/>

<!-- Plugin that sets up WebGLRenderer. Note that I'm providing 
  it with a context instead of a canvas. It makes it easier to 
  customize for advanced use case - like context sharing between 
  threlte and another webgl application.
-->
<RendererPlugin
  {rendererProps}
  {webglContext}
/>

<!-- This would call renderer.render(scene,camera), all 
  scene updating and useFrame stuff.  Everything that 
  happens whenever a frame is invalidated. 
  
  For custom solution, you could grab scene, camera, 
  renderer and everything user hooked into useFrame
  via context or props and compose it how they see fit.
-->
<FrameLoopPlugin />


<!-- Interactivity like we discussed during the meetup. Plugin included 
  in Canvas by default, but an opt-in behind a flag. -->
<InteractivityPlugin enabled={false}>
  <SceneGraphObject object={ctx.scene}>
    <slot />
  </SceneGraphObject>
</InteractivityPlugin>

<MorePlugins1/>
<MorePlugins2/>
<MorePlugins3/>
```
