### ISSUE TITLE
[next] "Enabling interactivity" section is in "legacy mode"

### ISSUE THREAD

**Issue by nshiab** [threlte/threlte#1221]
Hi!

I am discovering Threlte and going over the "Getting started" documentation here:
https://next.threlte.xyz/docs/learn/getting-started/your-first-scene

I just wanted to flag that this section is not using runes. I would be curious to see an updated section for V8.

I know you probably have a lot to do already. Congrats on the library and the doc. Very well done! :)

Cheers

**Comment by joshwashywash** [comment]
Hi @nshiab 

Welcome to threlte 😎 

I don's see anything in the "enable interactivity" section that is considered "legacy".

Do you mean the [spring store](https://svelte.dev/docs/svelte/svelte-motion#spring)?

**Comment by nshiab** [comment]
Hmmmm... I think you are right! But for some reason, the Svelte extension in VSCode flags the code as legacy.

Here's a basic component. It's flagged as "Runes mode."

<img width="969" alt="Screenshot 2024-11-29 at 4 39 11 PM" src="https://github.com/user-attachments/assets/27033263-fac3-4169-9371-ba67179cc86b">

But the App and Scene from the documentation are flagged as "Legacy mode" for some reason. Weird.

<img width="516" alt="Screenshot 2024-11-29 at 4 39 25 PM" src="https://github.com/user-attachments/assets/62601dab-8c3c-4aed-be01-c5a5146d41c9">

<img width="552" alt="Screenshot 2024-11-29 at 4 39 43 PM" src="https://github.com/user-attachments/assets/27648143-8574-4b28-859d-d19ae01e9953">

The spaceship tutorial looks AMAZING. I'll dive into it as soon as I have the chance. Thanks! :)

**Comment by joshwashywash** [comment]
oh that's interesting. i wonder if it defaults to legacy mode until you add something from runes.

**Comment by nshiab** [comment]
You are right! Sorry to have bothered you...

**Comment by joshwashywash** [comment]
Nah it was not a bother. 👍🏻
