### ISSUE TITLE
Default `dracoDecoderPath` ?

### ISSUE THREAD

**Issue by amr3k** [threlte/threlte#130]
Hi, I believe it's a common use case is to set the draco decoder path to `https://www.gstatic.com/draco/v1/decoders/`, Should threlte add it as default value?
specifically in this line:

https://github.com/threlte/threlte/blob/7e2e46db8c36fd67265d360f570191ccc5a7c654/packages/extras/src/lib/components/GLTF/GLTF.svelte#L33

This is a slightly improvement to help devs not to include that URL in every GLTF component in every project.

**Comment by grischaerbe** [comment]
Yes, I think there should be a default value. The hook [`useGltf` is providing that](https://github.com/threlte/threlte/blob/f8ba4d8ef7d80f2ef3a99f943fd345fbb28ae1c9/packages/extras/src/lib/hooks/useGltf.ts#L24-L33).
I'll add it to the roadmap. If you feel like contributing, feel free to give it a try!
