### ISSUE TITLE
Add recipes section

### ISSUE THREAD

**Issue by amr3k** [threlte/threlte#139]
Hi, as we discussed earlier on discord, it would be awesome to have some recipes for frequently asked questions like #71 

Is it suitable to put them in a separate section in the sidebar ?

**Comment by amr3k** [comment]
I'm willing to implement a prototype if you like.

**Comment by grischaerbe** [comment]
Hey @amr3k ! There's currently a PR draft "Examples & Playground" which would serve that purpose, is that what you think of?

**Comment by amr3k** [comment]
No but it's better than what I thought of , My initial request was to create a pre-made examples like any other example in the docs.

But with this PR, it will allow both pre-defined examples, and allow visitors to make their examples as well. (this is how I understand it).
Which is great.
