### ISSUE TITLE
Move Docs to new SvelteKit page endpoints

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#147]
The Docs are built with [KitDocs](https://github.com/svelteness/kit-docs), so we'd need to check their support first.

**Comment by davej** [comment]
Related: https://github.com/svelteness/kit-docs/issues/70

**Comment by grischaerbe** [comment]
We're moving to [Astro](https://astro.build/) with the [new docs](https://next.threlte.xyz) to have better markdown support.
