### ISSUE TITLE
Tweakpane code repetition

### ISSUE THREAD

**Issue by jerzakm** [threlte/threlte#151]
I've noticed that we're copying the same(?) tweakpane code between examples. Should we just put it in one place and import?

Maybe we could use a @threlte/utils package where non-three related code lives. Like this tweapkane thing, but also Keyboard controller proposed by @AlexWarnes on discord?

**Comment by grischaerbe** [comment]
I don't think it's a good idea to publish code that only the docs use. I rewrote the playground module collector to something a little bit more elaborate and it can now import any relative module as well. So imports like `import SomeThing from '../../../some-directory/module.ts'` is now possible.
