### ISSUE TITLE
Coloring Instance of InstanceMesh

### ISSUE THREAD

**Issue by AllanSCosta** [threlte/threlte#167]
Hey folks! First of all, fantastic job! I'm mindblown by the ideas and having a blast developing through Threlte :D 

I got stuck in trying to set the color of `Instance` objects dynamically. I'm setting up an environment which should be fairly modularized, and `<InstancedMesh>` is only bound to `<Instance>` indirectly, in a three-file level:

```svelte
(Mesh.svelte)

<script lang='ts'>
    import { MeshStandardMaterial, SphereBufferGeometry } from 'three';
    import { InstancedMesh } from '@threlte/core';
    const geometry = new SphereBufferGeometry(0.5, 8, 8)
    const material = new MeshStandardMaterial();
</script>
<InstancedMesh {geometry} {material} interactive >
    <slot />
</InstancedMesh>
```

```AtomGroup.svelte
(Sphere.svelte)
<script lang='ts'>
    import Sphere from './Sphere.svelte'
    import { Group } from '@threlte/core'
    import { Color } from 'three'
    let spheres = (...) code that sets up an array of props for Sphere instances (...)    
    let color = Color('red');
</script>

<Group>
{#each spheres as sphere}
    <Sphere {...sphere} 
        color={color}
    />
{/each}
</Group>


```

``` Sphere.svelte
(Sphere.svelte)
<script lang="ts">
  export let color;
</script>

<Instance
  position={position}
  color={color}
/> 
``` 

Interestingly, using the same pattern to dynamically set `scale` does work. Is this expected behavior? How should I go about it?
Allan

**Comment by grischaerbe** [comment]
The component `<InstancedMesh>` changed dramatically in [Threlte 6](https://threlte.xyz/docs/reference/extras/instanced-mesh), can you still reproduce that issue now? We will reopen then.
