### ISSUE TITLE
Threlte scene incorrectly sized and causes overflow in flexbox layout 

### ISSUE THREAD

**Issue by lauriegriffiths** [threlte/threlte#182]
When a Threlte scene is used in a flex layout without explicit sizes the scene matches its parent's parent size on page load (causing an overflow), but when content is changed the scene matches its actual parent.  

Here's a reproduction in the Svelte repl:

https://svelte.dev/repl/378434d4edb94fc794ed74797cbf60a4?version=3.53.1

**Comment by eriksachse** [comment]
Try this: 
```
import { onMount } from "svelte"
let show3D = false;
onMount(() => {
  show3D = true
})
```

On top of that there aren't explicit sizes, just one max-height.

**Comment by lauriegriffiths** [comment]
That's a good work around for a simple case, but there are still issues when other elements on the page change size.

Here's a simple example showing the problem:
https://svelte.dev/repl/hello-world?version=3.53.1

The 3D scene keeps its original size even when the other elements change size.  The two green bordered divs should have the same size.

**Comment by ixxie** [comment]
I believe that `<Canvas>` was designed to conform to its parent. If you want to control the size of a Threlte scene using CSS, simply put a canvas *without* size props inside another HTML element (say a `<div>`) and use CSS to resize that div.
