### ISSUE TITLE
Remove useless "space" inside canvas

### ISSUE THREAD

**Issue by seo-rii** [threlte/threlte#185]
The components that we create in threlte are, of course, virtual components. However, the spaces between these components are being rendered.
For example, in the example https://threlte.xyz/playground/introduction, if you look at the JS output: (Scene.svelte, L229)
```javascript
return {
  c() {
    create_component(three0.$$.fragment);
    t0 = space();
    create_component(gltf.$$.fragment);
    t1 = space();
    create_component(three1.$$.fragment);
    t2 = space();
    create_component(three2.$$.fragment);
    t3 = space();
    create_component(three3.$$.fragment);
    t4 = space();
    create_component(three4.$$.fragment);
  },
```

You can see the rendering of space as shown in .
This will have little impact on updates, but I think it can affect the initial rendering speed in complex apps. Currently, the thrlte is using a preprocessor, and it would be nice if you could use it to remove the space in the Canvas component, or at least replace it with a function that does nothing.

**Comment by grischaerbe** [comment]
It is possible that this changed with Svelte 4, at least [we cannot reproduce the issue in the Svelte REPL anymore](https://svelte.dev/repl/f405cfd71dd24b3db89fac7a4621a6b3?version=4.2.0).
If this issue still persists, can you link to a REPL?
