### ISSUE TITLE
Jae's first look notes

### ISSUE THREAD

**Issue by Honga1** [threlte/threlte#22]
Hey :) As we discussed! Some of this is superficial, just wanted to have somewhere to put everything I thought along the way. (Note I'm commenting without using it yet).

- Add noUncheckedIndexAccess to tsconfig
- Add noFallThroughCasesInSwitch to tscofig
- Rename / resize getting-started-screenshot (Doesn't need to be in static right? If it's in the readme).
- Don't mix casing styles in files (static / models vs screenshot)
- Can you drop the `default` keyword here? I don't know anything about svelte modules `export { default as OrthographicCamera } from './cameras/OrthographicCamera.svelte'` `export OrthographicCamera from 'OrthographicCamera'`
- https://github.com/grischaerbe/threlte/blob/55e63074077a7db6d032c5c58472373df7369fba/src/lib/types/components.ts#L14 Could be better to use interfaces whenever you can. https://www.typescriptlang.org/docs/handbook/2/everyday-types.html#differences-between-type-aliases-and-interfaces
- https://github.com/grischaerbe/threlte/blob/55e63074077a7db6d032c5c58472373df7369fba/src/lib/text/Text.svelte#L66 This sort of pattern could be factored, in which your intent would be more clear than the imperative form it's in currently
- https://github.com/grischaerbe/threlte/blob/55e63074077a7db6d032c5c58472373df7369fba/src/lib/objects/GLTF.svelte#L132 `scene?.traverse...`
- https://github.com/grischaerbe/threlte/blob/55e63074077a7db6d032c5c58472373df7369fba/src/lib/objects/GLTF.svelte#L134 I generally prefer early return and guard clauses as it keeps mental complexity / indentation down. `if(!objIsMesh()) return`
- https://github.com/grischaerbe/threlte/blob/55e63074077a7db6d032c5c58472373df7369fba/src/lib/objects/Mesh.svelte#L55 Why the form 'MeshInstance' vs the filename `Mesh`. Wouldn't these normally be the same?
- https://github.com/grischaerbe/threlte/blob/2571fb744d28d954de033dc2ce11e012ba153939/src/lib/lib/contexts.ts#L49 `thing[something] = (thing[something] ?? 0) + 1`
- `debugFrameloopMessage` sounds like a type. There's no context on the Frameloop in this scope. Probably better to name it `debugMessage`
- I see folders like `lib/controls`. These seem like the project could be broken into something like core / convenience. Kind of like drei/r3f. You can use a tool like `madge` to see your dependency graph to make the split. May help keep cognitive effort down in working in the codebase.
- `Threlte is a component library for svelte to build and render three.js scenes declaratively and state-driven in Svelte apps.` Do you batch the invalidations? This could be a good thing to mention because it allows you to debug frame budgets pretty easily.
- `It's inspired by the sensible defaults of [react-three-fiber](https://github.com/pmndrs/react-three-fiber), the simplicity and effectiveness of Sveltes reactivity model and [Svelte Cubed](https://github.com/Rich-Harris/svelte-cubed).` Maybe here it's good to mention what you do differently / the design goal of the lib.
- `It also aims to provide the building blocks to quickly extend threlte when it's needed.` Probably need more context on this. Maybe a snippet or something.
- Maybe the components section in your index can be flattened into a table like drei. So you can have a better overview in the readme.
- `Build your first scene:` You can unprettyfy the imports in the code snippet etc by inlining them. This will keep the focus on the parts that need focus.
- `It should look something like this:` Can cut the whitespace out of the image, compress properly and use a short gif maybe?
- In your code snippets `position: Position | undefined = undefined` could be a little prettier.

I haven't yet had a go at playing with it :) Will have to wait for next weekend. Got some dark souls to fail at.

**Comment by grischaerbe** [comment]
In the light of [Threlte 6](https://next.threlte.xyz) which is pretty much a complete refactoring, I think we can close this. Thanks again @Honga1 for your input!
