### ISSUE TITLE
Implement TrackballControls

### ISSUE THREAD

**Issue by crispy-landslide** [threlte/threlte#256]
Is there any plan to implement [TrackballControls](https://threejs.org/docs/#examples/en/controls/TrackballControls) in the future?

**Comment by grischaerbe** [comment]
Hey @crispy-landslide, we're working hard on the release of Threlte v6 which will separate concerns in terms of rendering and abstraction components. After that is done, implementing more controls is certainly on the roadmap. Feel free to join our [Discord Server](https://discord.gg/EqUBCfCaGm) to talk about future features!

**Comment by MattFerraro** [comment]
PR is [here](https://github.com/threlte/threlte/pull/799)!

**Comment by michealparks** [comment]
Added here: https://threlte.xyz/docs/reference/extras/trackball-controls
