### ISSUE TITLE
Using `useGltfAnimations` throws an Exception

### ISSUE THREAD

**Issue by gafert** [threlte/threlte#275]
Hello there! I tried adding animations via `useGltfAnimations` to a working component using GLTF which is documented here: https://threlte.xyz/extras/use-gltf-animations. First I wanted to list all actions, but regardless of how I use it the following error is thrown and the model is not rendered anymore. I have not seen any other mention that this is not working?

``` console
 useFrame.js:36 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'frameHandlers')
    at start (useFrame.js:36:19)
    at useFrame (useFrame.js:40:9)
    at useGltfAnimations (useGltfAnimations.js:46:5)
    at instance (ModelViewer.svelte? [sm]:3:18)
    at init (index.mjs:2016:11)
    at new ModelViewer (ModelViewer.svelte? [sm]:17:29)
    at createProxiedComponent (svelte-hooks.js?v=5cea0f8a:341:9)
    at new ProxyComponent (proxy.js?v=5cea0f8a:242:7)
    at new Proxy<ModelViewer> (proxy.js?v=5cea0f8a:349:11)
    at create_if_block (PortfolioElement.svelte? [sm]:16:41)
```

It references this line:

https://github.com/threlte/threlte/blob/0942910f8154706c5d80e5494568a8c42fe6764d/packages/core/src/lib/hooks/useFrame.ts#L52

# Minimal Example

A minimal project with the problem is hosted here: https://stackblitz.com/edit/threlte-usegltfanimations-epjmp?file=src/routes/ModelViewer.svelte

The component `ModelViewer.svelte` contains:

``` html
<script lang="ts">
    import {AmbientLight, Canvas, DirectionalLight, OrbitControls, PerspectiveCamera} from '@threlte/core'
    import {GLTF, useGltfAnimations} from '@threlte/extras'

    // TypeError: Cannot read properties of undefined (reading 'frameHandlers') exception when added
    // When removing `useGltfAnimations` the gltf is shown as expected.
    const {gltf} = useGltfAnimations(({actions}) => {
         console.log(actions)
    })
</script>

<Canvas>
    <PerspectiveCamera position={{ x: 10, y: 10, z: 10 }} near={10} far={10000} fov={24}>
        <OrbitControls autoRotate enableDamping/>
    </PerspectiveCamera>

    <DirectionalLight castShadow position={{ x: 10, y: 10, z: 10 }}/>
    <AmbientLight intensity={1}/>

    <GLTF
            bind:gltf={$gltf}
            url="/LittlestTokyo.glb"
            dracoDecoderPath="https://www.gstatic.com/draco/v1/decoders/"
    />
</Canvas>
```

**Comment by grischaerbe** [comment]
Hi @gafert,

This happens because `useGltfAnimations` relies on the context that is set by `<Canvas>` and as such this hook can only be used in a child component to `<Canvas>`. Check out the examples in the docs for a convenient go-to structure for your Threlte app: One component (e.g. "Scene.svelte") that is slotted in a `<Canvas>` component. In this Scene file you have access to the context and as such you're able to use this hook.

Also be sure to check out our Discord community! Lots of helpful people there!
