### ISSUE TITLE
Molecule and/or Crystal Structure Example

### ISSUE THREAD

**Issue by janosh** [threlte/threlte#280]
Would be cool if there was an example of how to render a 3D representation of a molecule or crystal structure, something that looks and behaves similar to the Materials Project interactive structure viewer.

[![Zr2Bi2O7 (mp-756175)](https://user-images.githubusercontent.com/30958850/218536428-c377f5e8-4b29-412c-995b-b7470976965c.png)](https://materialsproject.org/materials/mp-756175)

Atomic coordinates can be downloaded from Materials Project for 1000s of structures in JSON and other formats.

Example: [material_mp-754128_files.zip](https://github.com/Rich-Harris/svelte-cubed/files/7636096/material_mp-754128_files.zip)

**Comment by rowin-C** [comment]
The molecular structure of compounds comprises of sphere and cylinder so they relatively easy to make you just have to set their location , you can refer this article https://react-next-bog.vercel.app/articles/article5  and export 3D models of molecules from blender

**Comment by janosh** [comment]
@rowin-C Thanks for bumping this thread. Forgot to update that I started working on this over at https://elementari.janosh.dev/structure.

The barebones are there but it currently only handles cubic, orthorhombic and tetragonal crystals. I'm happy to make a PR to threlte with a demo for this component once it's more polished.

**Comment by ixxie** [comment]
I just got a contract for building a site for an aerosol physical chemistry research group; not quite lattice structures, but still relevant. I'm planning to build some molecules for the project, ill keep you posted on my progress.

**Comment by ixxie** [comment]
@janosh I sent you an email: I got permission to open-source the molecule code. Lets do it!

**Comment by ixxie** [comment]
@janosh I wonder if we should close this issue in favor of waiting until Elementari is a little more stable; we could then just link to Elementari from the Threlte docs, since the project uses Threlte!

**Comment by janosh** [comment]
Sure, I'd be happy to link to Elementari. Don't even need to wait, I can add a beta banner so people know there might be breaking changes down the line. Most probably just want to see the demos to know what _can_ be done and won't become users right away.

**Comment by ixxie** [comment]
Closing this - we will add Elementari to our new showcase page! https://github.com/threlte/threlte/issues/505
