### ISSUE TITLE
Are types enabled ? for gLTF ?

### ISSUE THREAD

**Issue by silicon-ninja** [threlte/threlte#294]
I was working extensively on gLTF  using this library 

while accessing a object wasn't able to auto-type the object so was wondering if its not typecast  

```ts
ThrelteGltf<{
    nodes: Record<string, any>;
    materials: Record<string, any>;
}>
``` 
this the type of threltegltf object and its is a svelte store was trying to access other properties using 
 
```ts
gltf.update(channel => {
   var some_obj = channel.nodes["blah"]
})
)
``` 

and it returns me a list of this type 

 ```typescript
 Record<String,any> 
 ```

now the problem is if i want to access an single object from the list i can't cause its of type `any` .  

happy to make a PR if required 

PS : raised a issue on discord channel [issue link](https://discord.com/channels/985983540804091964/1079661967951798346)

**Comment by grischaerbe** [comment]
Issue resolved on Discord
