### ISSUE TITLE
three v151 updates GroundProjectedEnv to GroundProjectedSkybox

### ISSUE THREAD

**Issue by ngsmcphrsn** [threlte/threlte#332]
Update import in [GroundProjectedEnv component](https://github.com/threlte/threlte/blob/d6b27bde4309637eaa56bc020acb47a289382c3f/packages/extras/src/lib/components/Environment/GroundProjectedEnv.svelte) to match v151, per https://github.com/mrdoob/three.js/pull/25645.

**Comment by grischaerbe** [comment]
Fixed in `'@threlte/extras@next'`.
