### ISSUE TITLE
Acceptance of donations to the project

### ISSUE THREAD

**Issue by henriquehbr** [threlte/threlte#345]
First, a huge thanks to all the developers involved on the making of this project, it has been of great help to me, not only it abstracts many of Three.js internals, but also synergizes very well with the way things are done on Svelte

I would like to give back to it in some way or another, but unfortunately, i don't have enough time to get into making code/documentation contributions, so i would like to know if the maintainer(s) are interested in accepting donations

**Comment by grischaerbe** [comment]
Hi @henriquehbr and thanks a lot for your interest to support this project! Threlte is now somewhat of a part-time second job for me and while I *absolutely love* working on it, seeing what people create with it and try to help where I can, it takes a lot of time. In an effort to make this project financially more sustainable I decided to give people the possibility to sponsor me: [https://github.com/sponsors/grischaerbe](https://github.com/sponsors/grischaerbe).
It not only helps me to find more time to work on Threlte but ultimately enables you to build on and with a product that's more stable, has better support and is progressing at the speed of light.

Also: I stated in the past that I don't want to make Threlte about me personally and I still stand by that. We're going to introduce a system that's fair to all collaborators and maintainers in the future and we are currently in the ideation phase of how such a transparent and fair system could be implemented to attract more collaboration from the outside.
