### ISSUE TITLE
Update with `threejs` rename of `GroundProjectedEnv` to `GroundProjectedSkybox`

### ISSUE THREAD

**Issue by 9a24f0** [threlte/threlte#349]
As of PR [#25645](https://github.com/mrdoob/three.js/pull/25645), `GroundProjectedEnv` got renamed to `GroundProjectedSkybox`, hence the import in `GroundProjectedEnv.svelte` is failed:

```js
import { GroundProjectedEnv } from 'three/examples/jsm/objects/GroundProjectedEnv';

...
        currentGroundEnv = new GroundProjectedEnv(envMap);
```

should be changed to 

```js 
import { GroundProjectedSkyBox } from 'three/examples/jsm/objects/GroundProjectedSkyBox';
...
        currentGroundEnv = new GroundProjectedSkyBox(envMap);
```

**Comment by grischaerbe** [comment]
Hey @9a24f0, this has already been fixed in `@threlte/extras@next`. Threlte 5 will not receive an update on this, I strongly suggest to [upgrade your application](https://next.threlte.xyz/docs/learn/advanced/migration-guide) if you haven't done yet.
