### ISSUE TITLE
Bug: GroundProjectedEnv renamed to GroundProjectedSkybox.js

### ISSUE THREAD

**Issue by pokatow** [threlte/threlte#350]
I was trying out the Threlte GLTF component and found an error
![image](https://user-images.githubusercontent.com/109038853/231660423-3b503dd5-a70c-4034-8585-bd16890b7dac.png)

I think in Three.js version 0.151.0^ the GroundProjectedEnv.js file has been renamed to GroundProjectedSkybox.js

https://unpkg.com/browse/three@0.150.1/examples/jsm/objects/

**Comment by ixxie** [comment]
Hey @pokatow, this has been fixed in `@threlte/extra@next`; see https://github.com/threlte/threlte/issues/349.
