### ISSUE TITLE
GroundProjectedEnv Module Not Found 

### ISSUE THREAD

**Issue by ayodyln** [threlte/threlte#356]
There was a class change to the file GroundProjectedEnv. Things break since at some point that file is being requested since ThreeJS changed the name of the file and the name of the class within that file. Things break when you run npm run dev.

Please refer to this issue: [GroundProjecedEnv Module Not Found #25852](https://github.com/mrdoob/three.js/issues/25852).

They recommended I submit an issue with this repository.

**Comment by bpm-mcgill** [comment]
Yeah I just fixed it by changing `GroundProjectedEnv` to `GroundProjectedSkybox`. You could probably submit a pull request making the name change.

**Comment by grischaerbe** [comment]
It's already fixed in the `next` branch for Threlte v6. Threlte v5 will not receive an update on this.

**Comment by grischaerbe** [comment]
See #343
