### ISSUE TITLE
Postprocessing on specific layers

### ISSUE THREAD

**Issue by FreddieRa** [threlte/threlte#36]
In three.js normally, it is possible to use selective passes (e.g. [here](https://threejs.org/examples/?q=bloom#webgl_postprocessing_unreal_bloom_selective) and [here](https://codepen.io/prisoner849/pen/LYLrawm)) by rendering multiple layers. 

Using the inbuilt postprocessing in Threlte is something similar possible natively (applying passes to specific layers ideally, but objects otherwise), or should I aim to recreate this effect the way it is done in examples?

**Comment by grischaerbe** [comment]
This is definitely something that needs a flexible hook into the rendercycle. It's something that's on the list and a priority in the next iterations. 
(PRs are highly welcome if you want to give it a shot 🙂)
