### ISSUE TITLE
three's GroundProjectedEnv has changed to GroundProjectedSkybox

### ISSUE THREAD

**Issue by whazami** [threlte/threlte#374]
Everything is in the title, it's just a little change so `extras` package can be correctly imported, in `extras/dist/components/Environment/GroundProjectedEnv.svelte`, all the `GroundProjectedEnv` should be changed to `GroundProjectedSkybox`.

**Comment by DefinitelyMaybe** [comment]
this has already been done in the @next release

**Comment by seo-rii** [comment]
To fix it without using `@next` version, create a file like `src/threlte_fix.js`.

```javascript
import {GroundProjectedSkybox} from 'three/examples/jsm/objects/GroundProjectedSkybox';

export {GroundProjectedSkybox as GroundProjectedEnv};
```

Then, add this to `svelte.config.js`.

```javascript
{
    kit: {
        alias: {
            ['three/examples/jsm/objects/GroundProjectedEnv']: 'src/threlte_fix'
        }
    }
}
```

**Comment by seo-rii** [comment]
I think this should be reopened. It's only fixed on `@next` version, and if you create new project with stable version, it continues to make same error.

**Comment by grischaerbe** [comment]
Hey @seo-rii,

I consider Threlte 6 to be more stable than Threlte 5 ever was. The release is very close, we should take steps to emphasize using Threlte 6 rather than Threlte 5.

**Comment by seo-rii** [comment]
I understand the intention to induce the use of threlte 6. But I think legacy support is also important. In particular, this is not a feature request or bug on edge cases, but a bug that prevents entire project creation in all cases. The only solution to this is to downgrade the three.js version or apply the proxy component above, but these solutions exist only in this issue and are nowhere in the official document. Existing users will type `npm up` into the console and explain what happened for a long time.

**Comment by DefinitelyMaybe** [comment]
Legacy support is important but not always above all other considerations. Thank you for pointing out the current solutions to the issue. They'll solve it for those who have the issue.
