### ISSUE TITLE
"interactivity" don't works on threlte@next

### ISSUE THREAD

**Issue by GeoffreyBrunet** [threlte/threlte#392]
Hello,
I'm following the threlte@next tutorial, and I have an error with "interactivity" at line 5 on my code, in following screenshot. Another screenshot is the error who says "TypeError: Cannot read properties of undefined (reading 'renderer')". I'm using typescript, not javascript, but have same error with js.

This is my threlte dependencies in my package.json.
"@threlte/core": "^6.0.0-next.7",
"@threlte/extras": "^5.0.0-next.13",
"three": "^0.152.2",
"@types/three": "^0.152.0",

<img width="1170" alt="code" src="https://github.com/threlte/threlte/assets/25690819/ca51c991-f572-43f7-a34d-ae4e1699044c">

<img width="1170" alt="error" src="https://github.com/threlte/threlte/assets/25690819/b342bfda-3cf6-472f-a2d1-d029a3701c1c">

Thank you !

**Comment by grischaerbe** [comment]
Hi @GeoffreyBrunet,
Check out the very [first section of the tutorial](https://next.threlte.xyz/docs/learn/getting-started/your-first-scene). There's also a section about the [recommended app structure](https://next.threlte.xyz/docs/learn/basics/context). You're invoking the plugin where it has no access to the context provided by `<Canvas>`. Feel free to [join our Discord community](https://discord.gg/EqUBCfCaGm) if you need help setting up your project 🙂
