### ISSUE TITLE
Support ConvexGeometry

### ISSUE THREAD

**Issue by LeoDog896** [threlte/threlte#393]
One of ThreeJS's addons, [ConvexGeometry](https://threejs.org/docs/?q=convex#examples/en/geometries/ConvexGeometry), is a lovely utility around [BufferGeometry](https://threejs.org/docs/#api/en/core/BufferGeometry) that makes it easy to construct meshes. Having a component for this in `@threlte/extras` would be great!

**Comment by ixxie** [comment]
`<T>` is extensible! Have a look at [this section of the docs](https://next.threlte.xyz/docs/reference/core/t#extending-the-default-component-catalogue) and give it shot; you should be able to extend it to enable simply doing `<T.ConvexGeometry>`. Please let me know if that works, so we can close the issue.

**Comment by LeoDog896** [comment]
Whoops, thanks!
