### ISSUE TITLE
Next docs: feature request: make the left navbar nicer to use

### ISSUE THREAD

**Issue by henrikvilhelmberglund** [threlte/threlte#394]
I found the left navbar a bit annoying to use when looking through the reference docs. 

1. Links are `block` instead of `inline-block` so the link clickable area covers the whole navbar instead of just the link text making it harder to scroll. This could be fixed by changing the `block` class to `inline-block` or adding `w-fit` to the links.
2. The nav element itself has padding on the left so when you scroll at the left you scroll the main content instead of the navbar. This could be fixed by removing the padding on the nav element and adding it to the child ul element instead.

These fixes could make scrolling easier in the reference docs.

**Comment by ixxie** [comment]
Thank you for the input! There is some ongoing discussion regarding the docs navigation, so there is a chance this will be revisited soon. 

I'm going to leave this open and when @grischaerbe reaches some decision about next steps we will keep you updated here!

**Comment by sateeshsai** [comment]
Also, the left navbar scrolls to the top on visiting any of its links. Makes it difficult going through Rapier section as you have to scroll all the way the bottom everytime .

**Comment by grischaerbe** [comment]
Closed by #441
