### ISSUE TITLE
Environment path in documentation/playground

### ISSUE THREAD

**Issue by inspiredlabs** [threlte/threlte#399]
I'm interested in looking at the `Environment` playground example, having just started reading the docs, it states:

> Pass absolute path to path. For example, if you are using Sveltekit and you put your files in `static/envmap/hdr` then path will be `/envmap/hdr/`

But, when I open this link: `https://threlte.xyz/extras/environment`, it throws `Cannot find "/examples/jsm/objects/GroundProjectedEnv" in three@0.152.2`.

I don't have an interactive canvas to get the explicit URL resources from the browser itself – is there a way that we can add them in this example, rather than `/hdr/`, `'shanghai_riverside_1k.hdr`, etc? 

The perf in the example is already really good, this is great work.

**Comment by ixxie** [comment]
Sorry for the slow response!

We are getting close to releasing Threlte 6, and its good idea to start migrating (its very stable already!). In any case the old docs are not maintained at the moment.

Do you run into this issue in the new docs: https://threlte.xyz/extras/environment
