### ISSUE TITLE
Missing prop "type" of component <Collider>

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#406]
The component summary of the component `<Collider>` of the package `@threlte/rapier` is missing the prop `type`.

**Comment by tarunsamanta2k20** [comment]
I'd like to look into this

**Comment by ixxie** [comment]
> @grischaerbe where is your component summary located? I would like to know either the file name or location.

https://github.com/threlte/threlte/blob/main/apps/docs/src/content/reference/rapier/collider.mdx

**Comment by DefinitelyMaybe** [comment]
I can see a `shapeType` on the Collider class but I cannot see a `type`. The `<Collider>` component has a `shape` prop which is equivalent to rapiers `shapeType`.

I think we can close this one.
