### ISSUE TITLE
Allow to change renderer to WebgpuRenderer

### ISSUE THREAD

**Issue by seo-rii** [threlte/threlte#425]
Starting with Chrome version 113, webgpu is basically available without flags. 
As a result, three.js' webgpurender is also actively being developed. 
(https://github.com/mrdoob/three.js/commits/dev/examples/jsm/renderers/webgpu)

I think it would be good to include an option to change renderer to webgpurender in the Canvas component.

**Comment by grischaerbe** [comment]
Hey @seo-rii,
with about [15% of global availability](https://caniuse.com/webgpu) we're unfortunately still not close to a wide adoption. There's no definitive threshold for me, but it's not exactly a priority. There will be a transitional period where we want to provide the best possible DX in terms of choosing the renderer. If you have any plans and ideas how we should do that, feel free to propose changes or [start a discussion on our Discord](http://chat.threlte.xyz/).
It is of course possible to easily change the renderer with the hook `useRender` in Threlte 6:

```ts
const renderer = new WebGPURenderer()
useRender(({ camera, scene }) => {
  renderer.render(scene, camera.current)
})
```

**Comment by seo-rii** [comment]
@grischaerbe I definitely understand your opinion. I just created this issue because there wasn't any issue about it.

**Comment by grischaerbe** [comment]
Yep and I appreciate it! I'm leaving it open to be aware of it 👍

**Comment by MattFerraro** [comment]
In the six months that have passed since June, it looks like we're up to 28.5% of all users, and 66.61% of desktop users!

I still think there's a while to go before this becomes too important. Maybe when either Safari or Firefox support it by default, it'll be time to revisit this?

**Comment by michealparks** [comment]
https://stackblitz.com/edit/vitejs-vite-rmq

@MattFerraro Here's a stackblitz showing a simple working WebGPU + Threlte setup. It's still a bit clunky when replacing the default renderer and the need for a custom resizer, but it's possible. There's definitely still more that we can do before the WebGPURenderer becomes the default to make swapping renderers more seamless.

**Comment by verekia** [comment]
Let me know when there is a way to do this in Threlte so I can add Threlte to https://github.com/verekia/three-gpu-ecosystem-tests

**Comment by DefinitelyMaybe** [comment]
Definitely anytime after Threlte 8 is released. Currently you can using our [`@next` release](https://next.threlte.xyz/docs/examples/renderers/webgpurenderer).

Also, 72.46% [global webgpu](https://caniuse.com/webgpu)!! :tada:
