### ISSUE TITLE
Make option to inject plugin statically

### ISSUE THREAD

**Issue by seo-rii** [threlte/threlte#426]
## Background
Dynamically injecting using `injectPlugin` in `@next` can be useful for many usecases, but in most cases, we only uses fixed module like `interactive()`. In this case, using injectPlugin can be annoying because we need to split 'World' and 'Scene' even they are very simple so it can written into one file.

## Proposal
Make `plugins` option into `Canvas`. This option accepts array of plugins. Make some internal component inside Canvas. Canvas just passes plugins properties into that component, and that component calls injectPlugin. It won't change any API for plugin, just making another wrapper method to inject fixed plugins easily.

<hr>

If you think this proposal is reasonable, I'll make PR for it!

**Comment by grischaerbe** [comment]
Hey @seo-rii,

so your proposal could look like this if I understand you correctly:

```svelte
<script>
  import { Canvas } from '@threlte/core'
  import { interactivity } from '@threlte/extras'
</script>

<Canvas plugins={[interactivity]}>
  <T.Mesh on:click={…} />
</Canvas>
```

Internally this would mean to invoke `plugins.forEach((plugin) => plugin())` in the component `<Canvas>`.

If I interpreted your propsal correctly, I'm all for it!

**Comment by seo-rii** [comment]
That's right, I'll going to write draft PR for this!

**Comment by seo-rii** [comment]
While writing the code, I found that the plug-in was delivered using setContext directly. Do you think it's right to make plugins ejectable? If you think it's right to make the plug-in ejectable, I'll work with the current work.

**Comment by grischaerbe** [comment]
What do you mean with ejectable?

**Comment by seo-rii** [comment]
Availability to revert specifit plugin's injection.

**Comment by grischaerbe** [comment]
I'd say this should be handled on a plugin or plugin props layer. It's not an easy feat to make plugins ejectable from a quick thought.

**Comment by DefinitelyMaybe** [comment]
Happy for this issue to be reopened. Going to close for now.
