### ISSUE TITLE
Setting position of T.PerspectiveCamera causes unexpected behavior

### ISSUE THREAD

**Issue by seo-rii** [threlte/threlte#427]
Setting T.PerspectiveCamera's position using an array causes strange errors such as camera movement during rendering. To maximize this, try inserting OrbitControl into the camera. This does not happen when each coordinate is specified separately, such as position.x.

You can identify this bug by creating a new local project by copying the code from https://threlte.xyz/getting-started#first-scene.

**Comment by grischaerbe** [comment]
Hey @seo-rii,

I'm not sure I understand your issue. What do you mean with "_camera movement during rendering_"? Can you make a screen recording? You're also linking to the documentation of Threlte 5, but passing an array to the prop `position` is only supported from Threlte 6 on.

**Comment by seo-rii** [comment]
Oh, never mind. This was a matter of example in the document. To be exact, `T.PerspectiveCamera` was not a problem, but `<OrbitControls maxPolarAngle={degToRad(80)} target={{y:0.5}}/>` was the problem. Target had to be specify x and z values too. I don't think there need any further action because @next removed this example.

**Comment by seo-rii** [comment]
I'll reverse my words. This was a kind of issue. I would appreciate it if you could refer to #438.
