### ISSUE TITLE
Identifying rigid bodies in collisions

### ISSUE THREAD

**Issue by davelange** [threlte/threlte#429]
Using rapier, it is sometimes necessary to identify what rigid body another rigid body is colliding with, in collision events.
Right now I have workaround where I set `userData` on the rigid body reactively, but it would be useful to identify rigid bodies declaratively, either through user data, or the rigid body handle.

Does this make sense?

Thanks!

**Comment by davelange** [comment]
Yes. In those events you have access to the rigid body/collider, but afaik there's no easy way to check if it's a specific element. We have access to the rigid body handle, but it seems that is a random uuid. 

For example, in a scene with a bunch of colliders, we check the `collisionenter` events on collider A: if it collided with collider B we want to run some arbitrary logic, but if it hit collider C we want to run something else.

I've managed to workaround this by setting the `rigidBody.userData`, but there's not a way of doing that declaratively,
 such as:
```
<RigidBody type="dynamic" userData={{ name: "foo" }}>
  ...
</RigidBody>
```
So I was wondering if there is some "proper" way of checking this that I don't know of.

**Comment by ixxie** [comment]
From what I can see in the docs and source code, there is no such API at the moment. There is some use of `userData` within the `<RigidBody>` component, but I think we could easily expose an addition prop to let Threlte users pass data declaratively in this way (@grischaerbe correct me if I am wrong).

**Comment by davelange** [comment]
Thanks for the reply. That would be a useful feature!

**Comment by grischaerbe** [comment]
Added to [@threlte/rapier@1.1.0](https://github.com/threlte/threlte/releases/tag/%40threlte%2Frapier%401.1.0), thanks!
