### ISSUE TITLE
Provide more plugins like lookAt by @threlte/extras

### ISSUE THREAD

**Issue by seo-rii** [threlte/threlte#439]
Wouldn't it be better to provide plug-ins like `lookAt` to `@threlte/extras` like `interactivity`?

**Comment by grischaerbe** [comment]
Absolutely! Feel free to make a PR for anything that you like to see 👍 
I'll close this issue as it's not specific enough. If you're thinking about a specific plugin you would like to see, feel free to join our [Discord](http://chat.threlte.xyz) and we'll discuss there or open a separate issue.
