### ISSUE TITLE
OrbitControls example does not work

### ISSUE THREAD

**Issue by nhtoby311** [threlte/threlte#465]
I follow the new example for using `<OrbitControls/>` from `@threlte/extras`, of Threlte v6 [here](https://threlte.xyz/docs/reference/extras/orbit-controls). And it prompt me error that it needs <Camera/> as its parents, while I already did so like in the example from the docs.

```svelte
<script>
	import { Canvas, T } from '@threlte/core';
	import { OrbitControls } from '@threlte/extras';
</script>

<Canvas>
	<Model/>

	<T.PerspectiveCamera makeDefault fov={90} position={[0, 0, 2]}>
		<OrbitControls autoRotate />
	</T.PerspectiveCamera>
</Canvas>
```

Errors:
![image](https://github.com/threlte/threlte/assets/52330522/7671d689-2500-4c37-8215-bf72a6270ef2)

**Comment by grischaerbe** [comment]
Thanks for reporting! ❤️
