### ISSUE TITLE
Best way to get component ref, and animate/set props with `useFrame`?

### ISSUE THREAD

**Issue by nhtoby311** [threlte/threlte#468]
I wonder what is the way to get component ref, and then have `useFrame` to animate it? I tried the `bind:this` from Svelte but that return me a `ProxyComponent`, and not sure how to do anything with this object.

My attempt: 
```svelte
<script>
	let lightRef;
        let tabletModelRef;

	useFrame(({ camera }, delta) => {
                //This return ProxyComponent, which is readonly props. Looking for a way to animate/change the ref props.
		if (tabletModelRef) {
			console.log('tabletRef', tabletRef);
                        console.log('lightRef', lightRef);
		}

	});
</script>

<T.DirectionalLight position={[0, 10, 10]} bind:this={lightRef} />
<TabletModel rotation={[-Math.PI / 12, -Math.PI / 12, 0]} scale={1} position={[0.7, 0.15, 0]} bind:this={tabletModel} />
```

![image](https://github.com/threlte/threlte/assets/52330522/0142a9d4-6e84-4e5c-b57c-87a0a5c68577)

**Comment by grischaerbe** [comment]
You can get a reference to the underlying Three.js object by binding to `ref`:

```svelte
<T.DirectionalLight position={[0, 10, 10]} bind:ref={lightRef} />
```

Feel free to join our [Discord](http://chat.threlte.xyz) to get support!
