### ISSUE TITLE
Threlte in REPL not working?

### ISSUE THREAD

**Issue by zahachtah** [threlte/threlte#493]
This simple RepL seems to get stuck. Is there a way to run Threlte in the svelte REPL?

https://svelte.dev/repl/eda0e887f854400a9644db541645f887?version=4.1.2

**Comment by grischaerbe** [comment]
Could be related: https://github.com/sveltejs/sites/issues/354

**Comment by grischaerbe** [comment]
I'm sorry @michealparks I had a stab at it after a Discord chat 😬 It was in fact a circular import in core (fixed in #518), I didn't check the other packages though.

**Comment by michealparks** [comment]
Looks like all except `@threlte/theatre` work: https://svelte.dev/repl/56ccf50c458c45c993d496e2f0588aff?version=4.2.0
