### ISSUE TITLE
@threlte/gltf CLI still requires @next suffix

### ISSUE THREAD

**Issue by Joshimello** [threlte/threlte#494]
The @threlte/gltf CLI is generating for a older version of Threlte.
npx @threlte/gltf@next still works, but no longer mentioned in the docs.

**Comment by ixxie** [comment]
You need to use the tag `@latest` or `npx` will use the cache. We are adding this issue to the backlog since we should have documented this.

**Comment by Joshimello** [comment]
Ahh understood, thanks a lot!
