### ISSUE TITLE
Autocompletion and type hints of `<T>` is buggy

### ISSUE THREAD

**Issue by ixxie** [threlte/threlte#503]
Autocompletion / intelisense of the `<T>` has various issues: suggestions don't always show up, and sometimes classes from Three.js are autoimported.

It seems this is due to https://github.com/sveltejs/language-tools/issues/776. A PR with a possible mitigation - https://github.com/sveltejs/language-tools/pull/1177 - has been in draft state since september 2021, so it seems this is not a priority for the `sveltejs/language-tools` team.

**Comment by DefinitelyMaybe** [comment]
Another issue to track progress on this: https://github.com/sveltejs/svelte/issues/4818

**Comment by DefinitelyMaybe** [comment]
Lots of progress has been made on this issue with the migration to svelte 5. Closing for now.
