### ISSUE TITLE
Look into porting blended occlusion of drei HTML component to Threlte

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#504]
Drei component: https://github.com/pmndrs/drei#html

**Comment by snk-js** [comment]
I hope you're all doing well. I've recently come across the issue "Look into porting blended occlusion of drei HTML component to Threlte #504," and I'm interested in contributing to resolving this task.

I've already begun exploring the existing code and the relevant functionalities. I have some ideas on how to effectively port the blended occlusion feature. If no one is currently working on this, would it be alright if I took this on?

**Comment by grischaerbe** [comment]
Absolutely, go ahead captain 🚀

**Comment by michealparks** [comment]
Fixed in https://github.com/threlte/threlte/pull/957
