### ISSUE TITLE
Add resources section to docs

### ISSUE THREAD

**Issue by ixxie** [threlte/threlte#513]
Its nice to link to other known resources from our docs.

Let's add a page to the `learn` section of the docs linking to valuable resources to Threlte learners.

Here is a tentative list:

Underlying libraries:
- https://threejs.org/
- https://www.rapier.rs/
- https://www.theatrejs.com/

GLSL:
- https://thebookofshaders.com/
- https://learnopengl.com/

**Comment by DefinitelyMaybe** [comment]
I think this one has been getting better over time 

https://www.webgamedev.com/

**Comment by eerkmen** [comment]
Can you assign this to me @ixxie?
I am planning to create Category Name:

Community and Learning Resources

Title name:
Further Reading

under `learn` section

**Comment by ixxie** [comment]
Sure thing @eerkmen, thanks for hopping in!

Please name the category `more` and call the page `resources`. I'm an advocate of brevity, so you I often asked for shortened names when reviewing things 😃
