### ISSUE TITLE
404ing link in docs example "Terrain with Rapier physics"

### ISSUE THREAD

**Issue by mknadler** [threlte/threlte#526]
Under `How does it work`, the link 404's: 
> 1. Similar to the [3D noise example](https://threlte.xyz/terrain), loop over the vertices of a PlaneGeometry, and use a noise map to create a heightfield array heights."

From poking at this locally it looks like the url needs a `.` prefixing the `/terrain`.

**Comment by grischaerbe** [comment]
Fixed in #527
