### ISSUE TITLE
Clean up doc links

### ISSUE THREAD

**Issue by DefinitelyMaybe** [threlte/threlte#536]
Easy contribution for someone to who's wanting to get involved.

Occasionally we'll bump into links like the one in this section:
https://threlte.xyz/docs/reference/extras/transitions#usage
where there's a reference to localhost 😅 

If someone could do a decent comb over the docs and sort those out that'd be super 🎉

**Comment by eerkmen** [comment]
On it!

**Comment by eerkmen** [comment]
On it! I am going to create a fork and then check and fix the documentation in apps/docs/src/content/reference/extras/ directory. Let me know if there is another directory that needs a similar fix!

**Comment by DefinitelyMaybe** [comment]
Well that was pretty good! thank you @eerkmen
