### ISSUE TITLE
Is useTexture working? (error in asyncWritable)

### ISSUE THREAD

**Issue by zinoch** [threlte/threlte#542]
I doubt useTexture hook is fully implemented yet in Threlte. I have been spent some time to make it work, but it kept showing asyncWritable error in the line 29 of useLoader.js file.
  
  _const store = asyncWritable(promise);_

I can tell useTexture does not support video texture like in Three.js but then even image based texture doesn't seem to work. Does anyone have suggestion to solve this limit?

**Comment by grischaerbe** [comment]
Hi @zinoch, as far as I can tell `useTexture` is working just fine. Can you provide a repro or show code how you're using it? Also yes, `useTexture` is for image textures only as it uses the `THREE.TextureLoader`. If you want to use a video as a texture, you want to use a [`THREE.VideoTexture`](https://threejs.org/docs/index.html?q=video#api/en/textures/VideoTexture).

If you're having trouble using the hook `useTexture`, feel free to [join our Discord server](http://chat.threlte.xyz) to ask for help 👍

**Comment by zinoch** [comment]
client.js?v=de321752:2005 THREE.WebGLRenderer: Property .outputEncoding has been removed. Use .outputColorSpace instead.
      warn @ client.js?v=de321752:2005
      
      client.js?v=de321752:2005 THREE.Texture: Property .encoding has been replaced by .colorSpace.
      warn @ client.js?v=de321752:2005
      
      asyncWritable.js:56 Error in asyncWritable: undefined
      (anonymous) @ asyncWritable.js:56


This is the error I see from chrome console. I use the exact same examples from [threlte.xyz ](https://threlte.xyz/docs/learn/basics/loading-assets#loading-textures)

**Comment by grischaerbe** [comment]
Can you provide a minimap repro?

**Comment by zinoch** [comment]
1. In Ubuntu 22.04
2. npm create threlte my-project
3. check every option
4. go to Scene.svelte in src>lib>components
5. in <script>
```
import { useTexture } from '@threlte/extras'
const map = userTexture('texture.png')
``` 
6. in <T.Mesh> below <T.BoxGeomoetry />
```
{#if $map}
<T.MeshStandardMaterial map={$map} />
{/if}

```

Actually I tried all possible combinations following the document page. I originally tried it on my own project, but then decided to check this in the sample page to isolate the problem. The box is shown as white in the above case. Some other cases, it does not even show up.

**Comment by zinoch** [comment]
I put a full relative path there, and now it works.
`src/lib/components/texture.png`

@grischaerbe Thanks for your help.

**Comment by grischaerbe** [comment]
@zinoch, this is not the correct way to do it.

`npm create threlte@latest` will create a SvelteKit app and install the required dependencies. Nevertheless under the hood, it's a SvelteKit app. Static files, like images, should go to "/static" (e.g. /static/image.png) and will be referenced – either in your DOM markup or in `useTexture` – with a leading slash: `useTexture('/image.png')`. This is not a SvelteKit or Threlte feature, this is a platform spec. A leading slash defines an absolute url whereas an url that does not start with a protocol or a `/` is considered a relative url, check out the [MDN docs](https://developer.mozilla.org/en-US/docs/Learn/Common_questions/Web_mechanics/What_is_a_URL#absolute_urls_vs._relative_urls) on the matter and the [SvelteKit docs about project structure](https://kit.svelte.dev/docs/project-structure#project-files-static).
