### ISSUE TITLE
Buggy behavior in the mobile menu (FF)

### ISSUE THREAD

**Issue by ixxie** [threlte/threlte#545]
Two issue pop up when using the mobile menu of the docs site in Firefox on Android:
  1. The hamburger button seems intermittently unresponsive to taps
  2. Occasionally closing the menu results in a null page

See the following screen recording:

https://github.com/threlte/threlte/assets/20320695/ae45c8ef-7606-48a1-bb49-6e13bc93d042

**Comment by grischaerbe** [comment]
The menu burger button seems to be broken after navigation, which is probably a side effect of the experimental Astro page transitions. @jerzakm if you have time on your hand, can you check that? I can also look into it but probably not before end of next week.

**Comment by grischaerbe** [comment]
Since #556 is merged, can this be closed now?
