### ISSUE TITLE
Font still loads from Google's CDN despite choosing to using a local font...

### ISSUE THREAD

**Issue by Ashvith10** [threlte/threlte#557]
Despite choosing a local font (a `.ttf`) format, in my case, Trokia still gets the font from the CDN, instead of using the one provided locally.

**Comment by grischaerbe** [comment]
Hi @Ashvith10, can you provide a repro such as a Stackblitz?

**Comment by Ashvith10** [comment]
@grischaerbe Would it be okay to continue this conversation on the Discord server? I've shared a reproducible example over there...

**Comment by grischaerbe** [comment]
Fixed with #559, thanks for noticing!
