### ISSUE TITLE
Getting warnings from the console, despite 'characters' and 'sdfGlyphSize' not being a required dependency.

### ISSUE THREAD

**Issue by Ashvith10** [threlte/threlte#560]
For some reason, I get this error while using  the `Text` component.:

![image](https://github.com/threlte/threlte/assets/113123021/d37b67ab-93e4-4aef-890a-b113699a131b)
*text for accessibility*
```console
<Text> was created without expected prop 'characters' client.js:2005:15
<Text> was created without expected prop 'sdfGlyphSize' client.js:2005:15
```
This has most likely something to do with #557 because even when I use them, it looks like the variables are passed as empty. `characters` is probably set as an empty string, and `sdfGlyphSize` is set to zero. When setting `sdfGlyphSize` to an arbitrary value, I get this:

![image](https://github.com/threlte/threlte/assets/113123021/8ce1f270-75f2-4bfa-927a-f38cb73c16a1)
*text for accessibility*
```console
WebGL warning: drawArraysInstanced: TEXTURE_2D at unit 0 is incomplete: The dimensions of `level_base` are not all positive.
```

**Comment by grischaerbe** [comment]
Fixed with #559
