### ISSUE TITLE
[xr] Provide fallback slot in `<XR>`

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#597]
XR apps are different to regular apps in that they do not need a manually set up camera. This means that if you launch an XR app, you're thrown in the potentially already visible scene but with the default camera, which looks dull:

<img width="884" alt="Bildschirmfoto 2023-09-04 um 23 55 50" src="https://github.com/threlte/threlte/assets/46897060/80c896b3-c000-498f-adfb-bd89d230a013">

We should think about providing a fallback slot in the component `<XR>` that renders its contents when the XR session has *not* been entered yet as opposed to the contents of the default slot:

```svelte
<XR>
  <Hand left />
  <Controller right />

  <svelte:fragment slot="fallback">
    <T.PerspectiveCamera makeDefault position={[10, 10, 10]}>
      <OrbitControls />
    </T.PerspectiveCamera>
  </svelte:fragment>
</XR>
```

**Comment by michealparks** [comment]
I had considered this as well! Would the behavior of `fallback` be basically this?

```svelte
<!-- user is in an active XRSession -->
{#if $isPresenting}
  <slot />
{:else}
  <slot name='fallback' />
{/if}
```

**Comment by grischaerbe** [comment]
@michealparks Yes, this is pretty much how I'd use it. currently, I'm going around this listening to the XR events, but this approach seems better 👍
