### ISSUE TITLE
[xr] Provide `<Head>` component

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#599]
Sometimes you want to attach stuff to the head: An `<AudioListener>` for example.

**Comment by michealparks** [comment]
Yes!

Any thoughts about calling it `<Headset>` I'm brainwashed by the DOM to think this as the native `<head>` tag

I had originally considered adding a hook, `useHeadset()`, because I was thinking about triggering events when users look in a particular direction. Do you think both the hook and the component should be added?

**Comment by michealparks** [comment]
I'm also not sure - and need to read deeper into - if it's better / worse / equivalent to return the [viewer pose](https://developer.mozilla.org/en-US/docs/Web/API/XRViewerPose) or to use the method [described here](https://stackoverflow.com/questions/64639081/how-do-you-get-the-position-of-the-vr-headset-in-three-js)

**Comment by grischaerbe** [comment]
I'm currently brute-forcing it like this:

```svelte
<script lang="ts">
	import { T, useFrame, useThrelte } from '@threlte/core'
	import { Portal } from '@threlte/extras'
	import { Group, Quaternion, Vector3 } from 'three'

	const { renderer, scene } = useThrelte()
	const camera = renderer.xr.getCamera()

	const group = new Group()

	const worldPosition = new Vector3()
	const worldQuaternion = new Quaternion()
	const worldScale = new Vector3()

	useFrame(() => {
		camera.getWorldPosition(worldPosition)
		camera.getWorldQuaternion(worldQuaternion)
		camera.getWorldScale(worldScale)

		group.position.copy(worldPosition)
		group.quaternion.copy(worldQuaternion)
		group.scale.copy(worldScale)
	})
</script>

<Portal object={scene}>
	<T is={group}>
		<slot />
	</T>
</Portal>
```

**Comment by michealparks** [comment]
Completed with https://github.com/threlte/threlte/pull/612
