### ISSUE TITLE
Docs - footer design suggestion

### ISSUE THREAD

**Issue by edsunman** [threlte/threlte#615]
I think the docs pages look great overall and are easy to navigate but the footer takes up quite a lot of space and I'm not sure the links are necessary (community links are visible on the right and getting started links are easily found in 'Learn').

Perhaps a smaller version of the footer could sit at the bottom of the main central section and not intrude on the sidebars (similar to tailwind docs).

Idea mock-up:

![footerIdea](https://github.com/threlte/threlte/assets/14927523/55081869-c918-4b26-9695-efd6a753d40e)

**Comment by ixxie** [comment]
@edsunman thanks for pointing this out. After discussion with the team, we agreed the current footer is a problem.

We decided to simply remove the footer altogether as a solution. @jerzakm will be making a PR for this soon.
