### ISSUE TITLE
Question: how to break out of the heirarchy?

### ISSUE THREAD

**Issue by homerjam** [threlte/threlte#621]
Hi,

First of all thanks and congrats on the release of v6!

Is there a way to add components to the scene/context without having them exist as child components of the canvas?

My goal is to add and remove objects within the main scene from page components in sveltekit.

I have managed to put together a hacky way of doing it but I feel like there must be an easier way - perhaps not leaning so heavily on setContext, or exporting the internalCtx in the Canvas component so that it can be used outside, or maybe a renderless parent component that creates the context so that the Canvas component can have sibling elements (eg. the rest of the sveltekit app).

I hope this makes sense!

**Comment by grischaerbe** [comment]
Hey @homerjam,

I answered your question on Discord, for reference, here's the answer:

> What you can do is forward all contexts to a certain page with svelte's getAllContexts and use <T> components there. I don't really recommend that because reasonability suffers a lot, but it's sure possible

> I suggest to use stores to communicate with your Threlte scene from outside

> There's no right or wrong here, with Threltemania (https://threltemania.xyz/) I did it the other way around: https://github.com/grischaerbe/threlter/blob/main/src/routes/%2Blayout.svelte
There's basically a UI (DOM) Portal and every route is slotted into the canvas
