### ISSUE TITLE
Steps for "Setting up dev environment" in CONTRIBUTING.md not correct.

### ISSUE THREAD

**Issue by danielclough** [threlte/threlte#634]
There is no script `dev` in [`package.json`](https://github.com/threlte/threlte/blob/main/package.json) as is required by the steps in [CONTRIBUTING.md](https://github.com/threlte/threlte/blob/main/CONTRIBUTING.md).

I tried `pnpm preview -- --host` but all routes are 404.

**Comment by ixxie** [comment]
I've noticed the same thing but thought I was doing something wrong 😄 

I'm going to look into it. For now, I can say that you can go into `/apps/docs` and run the dev server from there.

**Comment by ixxie** [comment]
Okay, we discussed this and discovered the original dev script was removed and we find it clearer to change the documentation to reflect this change.

Now merged with https://github.com/threlte/threlte/pull/687
