### ISSUE TITLE
Implement PointerLockControls?

### ISSUE THREAD

**Issue by amr3k** [threlte/threlte#68]
Hi, any plan to add [PointerLockControls](https://threejs.org/docs/?q=control#examples/en/controls/PointerLockControls) in threlte?

**Comment by grischaerbe** [comment]
Not yet but it sure is a good addition. Contributions are also very much appreciated, so if you feel like giving it a shot, I'd be more than happy also to assist!

**Comment by 416d72** [comment]
I'll do my best 🙏🏾

**Comment by grandstanding** [comment]
Also needed this, created a very rough implementation. Will tidy it up and open a PR when I get some more time.

https://github.com/grandstanding/threlte/blob/main/src/lib/controls/PointerLockControls.svelte

**Comment by DefinitelyMaybe** [comment]
Alternative implemention:
https://gist.github.com/DefinitelyMaybe/a4544d80b1ed0a93553c115f92d790ab

**Comment by grischaerbe** [comment]
Threlte 6: `<T is={PointerLockControls} args={[camera, renderer.domElement]} />`. If you think we need an abstraction in `@threlte/extras` (such as [`<OrbitControls>`](https://next.threlte.xyz/docs/reference/extras/orbit-controls)), please open a separate issue 👍 .
