### ISSUE TITLE
Check documentation for uses of TailwindCSS

### ISSUE THREAD

**Issue by ixxie** [threlte/threlte#729]
TailwindCSS is not a standard technology in the Svelte ecosystem, so it shouldn't be used in the documentation or examples. Some of our examples seems to use Tailwind, and this should be avoided in favor of vanilla css.

**Comment by DefinitelyMaybe** [comment]
In #786 I've made an effort towards this but I'll need to do a more thorough check before we're good on this front

**Comment by DefinitelyMaybe** [comment]
feeling good on this front, can anyone find any last stragglers here

**Comment by DefinitelyMaybe** [comment]
would like to close for now. happy to keep an eye out 👀

**Comment by ixxie** [comment]
Close it!
