### ISSUE TITLE
Recommended way of using LoadingManager?

### ISSUE THREAD

**Issue by silveltman** [threlte/threlte#76]
Since threejs typically takes some time to load, it is good practice to add a loading overlay on pages where the object in included in the first section. 

In ThreeJS we can listen with LoadingManager to the completion of the load. However, I can't get it to work using threlte. I tried putting the first piece of code from the Threejs website (https://threejs.org/docs/index.html#api/en/loaders/managers/LoadingManager) in component aswell as in my wrapper.  However, nothing is heppening. 

What would be the recommend way to doing this?

**Comment by grischaerbe** [comment]
This is on the (unreleased) roadmap and I hope rather easy to implement. There's a rather big update coming up, let's see if it's in there already.

**Comment by silveltman** [comment]
Awesome, great to have people like you working on these things 👐

**Comment by silveltman** [comment]
In the meantime, is it possible to do it the 'vanilla' way? If so, where would I best place this code, the scene component or the wrapper?
