### ISSUE TITLE
InstancedMesh with GLTF

### ISSUE THREAD

**Issue by awarebayes** [threlte/threlte#794]
Greetings, I was going to use GLTF + Instanced mesh but ran into an issue.
Basically I need to have two sophisticated meshes I need to instance. 
I tried using InstancedMesh but it does not work with gltf because it calculates bounding  

```jsx
<InstancedMesh>
	<PersonModel scale={0.009} />
	<Instance position.x={-2} position.y={0} />
	<Instance position.x={-2} position.y={1} />
</InstancedMesh>
```

This for some reason does not work with any model I tried.

Just using <PersonMesh> with positions also gives no results.

Note that I am using the Model Pipeline and generate it using official create threlte app.

I can link the models I use, but I guess almost any will work

**Comment by awarebayes** [comment]
The Generated JSX model was supposed to solve this issue completely, yet it persists. Under the hood the generated model uses `useGLTF` hook, which is said to support only one model

**Comment by grischaerbe** [comment]
Hey @awarebayes, I'm not sure I understand your question.
Please check out the documentation of [`<InstancedMesh>`](https://threlte.xyz/docs/reference/extras/instanced-mesh) and its sibling [`<InstancedMeshes>`](https://threlte.xyz/docs/reference/extras/instanced-meshes). Join [our Discord](http://chat.threlte.xyz) to get support. I'm going to close the issue, feel free to reopen.
