### ISSUE TITLE
Unable install package with svelte 5.0

### ISSUE THREAD

**Issue by tuemaytinh1981** [threlte/threlte#801]
I thinks Svelte 5.0 has many change in syntax code ... 

npm install three @threlte/core 
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: odm@0.0.1
npm ERR! Found: svelte@5.0.0-next.26
npm ERR! node_modules/svelte
npm ERR!   dev svelte@"^5.0.0-next.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer svelte@">=4" from @threlte/core@7.0.12
npm ERR! node_modules/@threlte/core
npm ERR!   @threlte/core@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! 
npm ERR! For a full report see:
npm ERR! /Users/maitrongtue/.npm/_logs/2023-12-19T12_34_49_531Z-eresolve-report.txt

**Comment by grischaerbe** [comment]
Hi @tuemaytinh1981, Svelte 5 support will necessitate a major rewrite. The Svelte 5 API is not yet stable, so our efforts are limited currently. Stay tuned for updates!
I will close this issue, we'll open a separate issue once Svelte 5 is stable and our efforts get serious. 🙂
