### ISSUE TITLE
The default Threlte example won't work 

### ISSUE THREAD

**Issue by AmeerArsala** [threlte/threlte#805]
https://threlte.xyz/docs/examples/shaders/interactive-shader doesn't work because the Canvas has the error 
```
Object literal may only specify known properties, and 'children' does not exist in type '{ colorManagementEnabled?: boolean | undefined; colorSpace?: ColorSpace | undefined; dpr?: number | undefined; renderMode?: "manual" | "always" | "on-demand" | undefined; ... 6 more ...; ctx?: ThrelteContext | undefined; }'.ts(2353)
```

literally for no reason other than existing after much testing I found

**Comment by DefinitelyMaybe** [comment]
Could you please add some context. I just navigated to the same link on an android mobile and it works just fine

**Comment by jerrygreen** [comment]
I am experiencing this, too.

Even the most starter-app example: https://threlte.xyz/docs/learn/getting-started/your-first-scene

The rectangle is rendered, yes – if you place it into some div. But it throws a type error.

![image](https://github.com/threlte/threlte/assets/13215662/e3c175dc-ce0e-4139-82a9-857f43c6d559)

```json
"@sveltejs/kit": "^2.0.0",
"@sveltejs/vite-plugin-svelte": "^3.0.0",
"svelte": "4.2.12",
"@threlte/core": "7.1.0",
"@types/three": "0.161.2",
"three": "0.161.0"
```

The scene is:

```svelte
<T.Mesh>
  <T.BoxGeometry />
  <T.MeshBasicMaterial />
</T.Mesh>
```

**Comment by DefinitelyMaybe** [comment]
Hey thanks for posting the report.

It sounds like a weird error, like something react would do. Svelte doesn't have a notion of children atm but if you were using react then it'd probably try looking for 'children'

**Comment by jerrygreen** [comment]
I am not using react. I'm using Svelte.

You can see my entire lock file of all packages installed searching react, there's no a single mention of react:

![image](https://github.com/threlte/threlte/assets/13215662/eb58e101-f5b9-412f-898e-0dbeb3429c61)

**Comment by jerrygreen** [comment]
It seems after restarting VSCode, it now properly reads those types. Solved for me.

**Comment by DefinitelyMaybe** [comment]
good to hear! thank you for posting a possible fix for folks 😄

**Comment by grischaerbe** [comment]
The Svelte language server hangs up from time to time, so you can just restart from the command palette of VS Code 👍
