### ISSUE TITLE
Gizmo click detection is off by a constant

### ISSUE THREAD

**Issue by MattFerraro** [threlte/threlte#809]
I have a Gizmo on a page that includes an app bar and a tool bar:

![Screenshot 2023-12-30 at 10 16 38 AM](https://github.com/threlte/threlte/assets/1302431/7275d737-b73a-4ae3-9c7f-88ab20470cdb)

When I click on the X, -X, Z, -Y, buttons, the Gizmo does not respond. It behaves as though it is not receiving mouse clicks.

BUT, when I press the Y button, the camera moves to -Y. After some experimentation I found that the gizmo is receiving click events from the following locations:

![Screenshot 2023-12-30 at 10 16 38 AM](https://github.com/threlte/threlte/assets/1302431/e4836967-b433-49cc-b80c-247c9de6174d)

So I suspect there's a hardcoded assumption somewhere that the `<Canvas>` extends to the top of the viewport.

**Comment by MattFerraro** [comment]
Digging in a bit, the assumption seems to be made on [this line](https://github.com/threlte/threlte/blob/a85cf5d3940e41ad667f4a191e2a01a03404aa21/packages/extras/src/lib/components/Gizmo/Gizmo.svelte#L104)

I'll see if I can make a patch!

**Comment by MattFerraro** [comment]
PR is here: https://github.com/threlte/threlte/pull/810

**Comment by DefinitelyMaybe** [comment]
closing for now. We have a [new gizmo](https://next.threlte.xyz/docs/reference/extras/gizmo) since #1254 was merged 🎉 

happy for the issue to be reopen by OP if needed
