### ISSUE TITLE
Resizing browser seems to break renderer

### ISSUE THREAD

**Issue by franknoirot** [threlte/threlte#817]
Hi there, apologies if this is a THREE.js issue, I haven't been able to find any instances of it in their forums either.

I am using the `<Canvas>` component [here in my source code](https://github.com/KittyCAD/text-to-cad-ui/blob/sidebar-layout/src/routes/(sidebarLayout)/view/%5BmodelId%5D/+page.svelte#L83-L85), and [this is where I load a gLTF model into it](https://github.com/KittyCAD/text-to-cad-ui/blob/sidebar-layout/src/components/ModelPreviewer.svelte).

Whenever a user resizes the browser, at the point when the canvas starts to be resized my scene seems to break, disappear, or possibly be reduced to 0px in one or both dimensions:

https://github.com/threlte/threlte/assets/23481541/f2861e5c-3e27-4556-bfea-5a1f78fe9e30

I thought that [invalidating the render manually whenever `$threlteSize` changed might help](https://github.com/KittyCAD/text-to-cad-ui/blob/sidebar-layout/src/components/ModelPreviewer.svelte#L13-L17), but it doesn't seem to have.

Am I missing something obvious in [the docs on `useThrelte()`](https://threlte.xyz/docs/reference/core/use-threlte) that I can use in this scenario, or [am I perhaps abusing the way that `<T.OrthographicCamera>` is meant to be used](https://github.com/KittyCAD/text-to-cad-ui/blob/sidebar-layout/src/components/ModelPreviewer.svelte#L48-L57)?

**Comment by grischaerbe** [comment]
Hi @franknoirot,

You likely missed to add the prop `manual` to your camera, see this paragraph of the docs: https://threlte.xyz/docs/reference/core/t#camera-props.

I'll close it for now, feel free to reopen if that doesn't solve your problem 🙂
