### ISSUE TITLE
<Grid/> err: Shader chunk "encodings_fragment" has been deprecated.

### ISSUE THREAD

**Issue by jerzakm** [threlte/threlte#818]
Issue raised on discord. 

I think this is part of the fragment is outdated. It's probably related to the recent color changes. Should look into when the change occured, fix and maybe update the three peer dependency in extras. 

https://github.com/threlte/threlte/blob/main/packages/extras/src/lib/components/Grid/gridShaders.ts#L151

**Comment by R3D2** [comment]
I think I have something related to this that popped app after upgrading my app.

Uncaught Error: Cannot resolve #include <colorspace_fragment>

**Comment by michealparks** [comment]
Fixed in https://github.com/threlte/threlte/releases/tag/%40threlte%2Fextras%408.9.0
