### ISSUE TITLE
`<Gizmo />` not reacting to click events

### ISSUE THREAD

**Issue by janosh** [threlte/threlte#849]
I may have a similar issue as #809 where the `<Gizmo />` component does not react to click events. I tried clicking all around it to see if the active area was misplaced but didn't manage to find it. I did this with both `@threlte/extras@8.5.0` including the fix in #810 and `@threlte/extras@8.1.1` without it. Neither case worked for me.

Still actively debugging this over at https://elementari.janosh.dev/structure. Relevant commit: https://github.com/janosh/elementari/pull/46/commits/e6d7ca96e1.

**Comment by janosh** [comment]
can confirm my issue is similar to https://github.com/threlte/threlte/issues/809. the `Gizmo` `clickTarget` is far outside the canvas.

![Screenshot 2024-03-22 at 09 31 49](https://github.com/threlte/threlte/assets/30958850/51eed969-6d30-499b-89f7-6d067e6150c4)

not easy to debug this as changing the code in `node_modules/.pnpm/@threlte+extras@8.10.3_svelte@4.2.12_three@0.162.0/node_modules/@threlte/extras/dist/components/Gizmo/Gizmo.svelte` has no effect, maybe because `vite` actually loads an optimized/transpiled version of the code from somewhere else?

**Comment by michealparks** [comment]
Yep, I think the only way to realistically debug this is to clone + download the threlte repo and run the docs or extras playground locally. I've been meaning to look at this issue myself since I use gizmo a lot but unfortunately haven't had the time lately :(

**Comment by DefinitelyMaybe** [comment]
closing for now. We have a [new gizmo](https://next.threlte.xyz/docs/reference/extras/gizmo) since #1254 was merged 🎉 

happy for the issue to be reopen by OP if needed
