### ISSUE TITLE
Type inference for `useGltf` always returns `any` 

### ISSUE THREAD

**Issue by TimoWilhelm** [threlte/threlte#883]
I'm trying to use the `useGltf` hook from `@threlte/extras` to load a model. I specified the GLTF scene graph objects but the `AsyncWritable` is always of type `any` and I can't get autocomplete working in VSCode. 

![Screenshot 2024-02-19 190447](https://github.com/threlte/threlte/assets/22396907/8dd5c072-2ef7-438a-a72c-cf6a8bd018cc)

```ts
  type GLTFResult = {
    nodes: {
      Suzanne: THREE.Mesh
    }
    materials: {}
  }

  const gltf = useGltf<GLTFResult>('/path/to/model.glb', { useDraco: true })
```

Thanks in advance!

**Comment by DefinitelyMaybe** [comment]
Hey, sorry your having troubles with types. Partly, everyone is waiting for better type support upstream.

in the mean time, in your picture theres this
```ts
const gltf: AsyncWritable<any> = useGltf<GLTFResult>('/path/to/model.glb', { useDraco: true })
```
but I take it that the `: AsyncWritable<any>` isn't within your code?

**Comment by TimoWilhelm** [comment]
Yes, sorry for the confusing picture. The grey type definitions are just a highlight from the IDE showing the automatic inferred type definitions. Looking forward to improved type support!
