### ISSUE TITLE
InstancedSprite.svelte unused export with vite-plugin-svelte

### ISSUE THREAD

**Issue by BCsabaEngine** [threlte/threlte#917]
node_modules/@threlte/extras/dist/components/FakeGlowMaterial/FakeGlowMaterial.svelte3:59:12 PM [vite-plugin-svelte] /Users/csababalazs/Development/segmentcontroller/pcb-tht-holder/node_modules/@threlte/extras/dist/components/InstancedSprite/InstancedSprite.svelte:15:11 InstancedSprite has unused export property 'filter'. If it is for external reference only, please consider using `export const filter`
```
13: export let playmode = 'FORWARD';
14: export let count = 1000;
15: export let filter = 'nearest';
               ^
16: export let alphaTest = 0.1;
17: export let transparent = true;
```
when "@threlte/extras": "^8.10.1" -> "8.11.0"

**Comment by jerzakm** [comment]
Thanks for reporting, will be fixed in the next patch release @BCsabaEngine 🫡
