### ISSUE TITLE
Canvas expands indefinitely

### ISSUE THREAD

**Issue by manuel3108** [threlte/threlte#928]
I'm currently creating a composer / adder for threlte. [`svelte-compose`](https://github.com/svelte-compose/svelte-compose) will become the official successor of [`svelte-add`](https://github.com/svelte-add/svelte-add)

Tracking issues:
- https://github.com/svelte-add/svelte-add/issues/296
- https://github.com/svelte-compose/svelte-compose/issues/8

`svelte-compose` is still in a pretty early state but it's already quite usable. Using `svelte-compose` is also the easiest way to replicate this issue. Please proceed with the following steps in your terminal to replicate this:
```sh
npx @svelte-compose/threlte --path ./temp
# select to create a new project
# select to create a new `svelte` project (kit is not properly implemented at this point for the threlte composer)
# select javascript or typescript 
```

That's it. You now have a new svelte-project setup, where you can reproduce the issue. (You can also use this on an existing project, but that's not the point here)

Now install your dependencies and run your dev server as usual. You will see that the `canvas` element keeps expanding it's size for whatever reason:

https://github.com/threlte/threlte/assets/30698007/226b91f8-84a0-4128-9b53-190be2484b43

But as soon you remove the content from the `main` element, everything starts working again as expected.

---

As the goal is to modify the projects `svelte-compose` is used in to the smallest degree possible, I would like to avoid removing everything else in this svelte component.

In order to apply the composer, I'm following the instructions given in the [docs](https://threlte.xyz/docs/learn/getting-started/installation) as close as possible. You can find the source-code of the composer [here](https://github.com/svelte-compose/svelte-compose/blob/main/projects/composers/threlte/config/composer.js)

Note: I was not intending to publish the composer at this point, because it's pretty much wip. But since this is the easiest way to reproduce, I thought why not.

**Comment by DefinitelyMaybe** [comment]
hey! good to hear about your project, I hope it goes well for you 😃 

The issue above appears to be css related. threlte does do some automatic resizing based on the space it's been given. I'd recommend playing around with your css first. For example, you could put a `div` around the `Canvas` and then giving it `absolute` positioning as well as a particular size, e.g.

```html
<div style="position: absolute;top: 0px;left: 0px;width: 300;height: 300;">
	<Canvas>
		<Scene/>
	</Canvas>
</div>
```

**Comment by manuel3108** [comment]
Thanks, that indeed seems to help!
Is this a requirement that we always need to wrap the scene with a fixed size? I could not find anything regarding this topic inside the docs.

But even ignoring that, it seems weird that everything starts working once the `main` tag is empty. 

Based on my testing it seems to be enough to just wrap the canvas inside an empty div like this
```html
<div>
    <Canvas>
        <Scene />
    </Canvas>
</div>

<main>
    <!-- all the content of main as shown in the video -->
</main>
```

Overall this seems like a pretty strange behavior in my opinion.

**Comment by DefinitelyMaybe** [comment]
Good stuff 😄

Definitely not a requirement. It's contextual/use-case dependant.

Threlte does the resizing because it's a very very common issue that comes up with 3D web dev.

There's some info about it with the docs here: https://threlte.xyz/docs/reference/core/canvas
