### ISSUE TITLE
`<Edges />` component is duplicating (and more) its parent components click handlers (and possibly other events)

### ISSUE THREAD

**Issue by tsdexter** [threlte/threlte#948]
When adding a simple click handler to the "[Click, pointer, and wheel events](https://threlte.xyz/docs/learn/basics/handling-events)" example, the handler is fired twice on a click making it useless for something like a toggle which will always toggle to the opposite then back to the original. 

Any idea why it's doing this/what I'm doing wrong? 

Here is a reproduction, check the console to see the double logs. The `scale` and `color` should be changed by the toggle, but it's firing twice, too fast to even see a flash of change. https://stackblitz.com/edit/jdcepo?file=src%2Fexample%2FBox.svelte,src%2Fexample%2FApp.svelte 

If you uncomment line 24: `// toggle = false;` and then click, you can see that the `scale` and `color` based on `toggle` value does work

**Comment by tsdexter** [comment]
fyi: it's happening on the `mesh` and even the `Box` component. If you modify the `setRandomPos` you can see that it creates/sets two random positions, you just don't notice in the UI as it only moves to the last one:

```js
const setRandomPos = () => {
    const rp = {
      x: Math.random() * 10 - 5,
      z: Math.random() * 10 - 5
    };
    console.log(`setting rp`, rp);
    pos.set(rp)
  }
```

results in: 

```
clicked tjinp5z79urrg5d4ozig8
toggle {toggle: false}
setting rp {x: 2.0543025721258683, z: 2.2970634165024713}
clicked tjinp5z79urrg5d4ozig8
toggle {toggle: true}
setting rp {x: -4.070531010761296, z: 0.9007766565324111}
```

**Comment by tsdexter** [comment]
OK, I think I've found the real culprit.

The `<Edges />` component seems to be randomly cloning/reproducing click handlers from its parent. See in this new [reproduction ](https://stackblitz.com/edit/jdcepo-tpynpe?file=src%2Fexample%2FScene.svelte,src%2Fexample%2FApp.svelte,src%2Fexample%2FBox.svelte,src%2Fexample%2FCamera.svelte)that uses the Edges component, when you click a green box, it has differing amounts of console logs. Click the `add box` button to add some more boxes, then click those boxes and they all have different, seemingly random amount of console logs. Take out the `<Edges />` component and all the clicks only log once, as expected. 

That being said, [the comment above](https://github.com/threlte/threlte/issues/948#issuecomment-2067132531) isn't the actual issue I was having, but it does still seem to be happening - is that intentional?

**Comment by DefinitelyMaybe** [comment]
good to hear you've found your culprit 😄 

Still playing around with the stackblitz for handling events myself.

**Comment by tsdexter** [comment]
Yes - it's good to know the real cause. It was a real head scratcher trying to figure out what was going on. I think it's loosely related to the amount of Edges as some of my models were "clicking" up to 50x on a single click. 

I'll see if I can dig into the `<Edges />` component to find and out why and/or submit a PR when I get some time, for now, I'll just have to remove the component and catch up from the time I spent debugging it 😂

**Comment by DefinitelyMaybe** [comment]
found it! The event was propagating. [stackblitz](https://stackblitz.com/edit/ej4czt?file=src%2Fexample%2FScene.svelte)

**Comment by tsdexter** [comment]
Thanks for looking into it! 

I understand that clicking on an area of the canvas would trigger a click event that propagates through every element intersecting the ray. Looking at the `event.intersections`, in this case, it's all of the `LineSegments` from the Edges component as well as the `Mesh`, hence the 13 logs.

That being said, it's not clear to me why the click event propagating to each of the `LineSegments` is using the click handler from the `Mesh`? Shouldn't each `LineSegment` run its own click handler when the event propagates to it? 

I'm not understanding in what scenario I would want my click handler to run multiple times, once for every nested object. Perhaps, an example in the docs where this would be the desired outcome would be beneficial.

**Comment by DefinitelyMaybe** [comment]
hmm good question about the why. Best someone more knowledge describes that, I'm not too sure myself 😅
