### ISSUE TITLE
stencil needs to be manually enabled starting from threejs 0.163.0 for Mask to work

### ISSUE THREAD

**Issue by brennerm** [threlte/threlte#958]
Hey, I noticed the Mask component suddenly stopped working for me so I did some digging. Turns out the stencil buffer, starting from Three.js 0.163.0, is now disabled by default, breaking the Mask component.

To re-enable it, the appropriate renderer parameter needs to be set to true like so:

```
<Canvas rendererParameters={{ stencil: true }}>
  <Mask id={1}>
...
```

Creating this issue for two reasons:

1. Hope that others having the same issue come across it.
2. To find an approach how to deal with it in Threlte.

Personally I see two possible solutions.

1. Add a hint in the docs that tells users to make sure that the stencil buffer is enabled in the renderer.
2. The Mask component automatically taking care of enabling it, e.g. in the onMount method.

Not sure if there could be some unwanted side effects from enabling the stencil buffer when going with approach 2 though.

Let me know what you think! :slightly_smiling_face:   

References:
- [Three.js 0.163.0 Release Notes](https://github.com/mrdoob/three.js/releases/tag/r163)
- [PR setting stencil to false by default](https://github.com/mrdoob/three.js/pull/27900)

**Comment by DefinitelyMaybe** [comment]
Thank you for the update! I'm happy to jump into option number 1. We could also add some warnings to the component ☺️
