### ISSUE TITLE
three.js's example..GroundedProjectedSkybox has changed to GroundedSkybox

### ISSUE THREAD

**Issue by LeoDog896** [threlte/threlte#970]
https://github.com/mrdoob/three.js/commit/36f9019186a01ba481023dcfb12d3856c149f139#diff-6d839b9e72b180b37e6082e5f5d11f03e14be8af4e6973f6c57fa4410453a902

Similar to #374, but it seems as if the API for GronudedSkybox has changed.

**Comment by michealparks** [comment]
This was fixed in [@threlte/extras@8.5.1](https://github.com/threlte/threlte/releases/tag/%40threlte%2Fextras%408.5.1). Have you upgraded to latest?

**Comment by LeoDog896** [comment]
thanks - didn't see this!
