### ISSUE TITLE
Is Threlte going to be compatible with Svelte 5 ?

### ISSUE THREAD

**Issue by soleuniverse101** [threlte/threlte#973]
At the moment, I cannot use Threlte with the currently available (and experimental) Svelte 5 package and I haven't investigated much to know why, but I think it's because Threlte imports in some parts the "svelte/internal" module, which is not recommended to use in Svelte 4, and which will be removed completely in Svelte 5. Is this module necessary or would it be possible to do without using it ?

**Comment by jerzakm** [comment]
Threlte is going to be compatible with Svelte5 as quickly as it's reasonably possible. It's already in the works! I wouldn't use it for anything production grade yet but you can already use the Svelte5 version via the `next` tag in package.json (`@threlte/core@next` etc)

**Comment by michealparks** [comment]
If you check out our[ releases page](https://github.com/threlte/threlte/releases) you can find the latest Svelte 5 compatible `next` version to NPM install. It should work - with minor known issues - but like @jerzakm said it's probably safe not to do anything production-related with it until Svelte 5 and Threlte 8 exit `next` status. If you do use it and find issues, please report them!

**Comment by soleuniverse101** [comment]
Oh great I didn't know there was a next version. It works now, thank you!

**Comment by cristianvogel** [comment]
I'd like to give it a spin... how do I get the latest next? `npm i threlte@next` doesn't seem to do it

**Comment by michealparks** [comment]
You can follow the [install instructions](https://threlte.xyz/docs/learn/getting-started/installation) but add `@next` to the end of every package. For example:

```
npm i --save-dev @threlte/core@next
```

**Comment by wmurphyrd** [comment]
A couple helpful things I've found for working with svelte 5 preview

Documentation preview for the next branch: https://next.threlte.xyz/docs/learn/getting-started/introduction

Create project with svelte 5 & threlte next: `npm create threlte@next`
