### ISSUE TITLE
Bug: loading glb object with `morphTargetInfluences` and `morphTargetDictionary` gives error

### ISSUE THREAD

**Issue by adamhemzal** [threlte/threlte#981]
I'm using a [Ready Player Me](https://readyplayer.me/) avatar. I'm loading the avatar using `useGltf()`, and it works fine. However, when I use `?morphTargets=Oculus Visemes`, an error occurs. The URL without `?morphTargets=Oculus Visemes` produces a 3D model without `morphTargets` like `morphTargetDictionary` and `morphTargetInfluences`. I need `morphTargets` to change the mouth shapes and make my avatar come alive.

Here is my `Scene.svelte`

```javascript
// Scene.svelte
<script>
  import { Canvas } from "@threlte/core";
  import Avatar from "./old_Avatar.svelte";
</script>

<section class="relative pointer-events-none top-0 right-0 w-60 h-60 bg-transparent overflow-hidden border-brand-500">
  <Canvas>
    <Avatar position={[0, -1.9, -1.5]} />
  </Canvas>
</section>
```

Here is my `Avatar.svelte`

```javascript
<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 model.glb --transform
-->

<script>
  import { Group } from "three";
  import { T, forwardEventHandlers } from "@threlte/core";
  import { useGltf } from "@threlte/extras";

  export const ref = new Group();
  // 👇 problem occures here
  const gltf = useGltf('https://models.readyplayer.me/666187b49b677241db2b8030.glb?morphTargets=Oculus Visemes') 
 // 👆 problem occures here 
 const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
  {#await gltf}
    <slot name="fallback" />
  {:then gltf}
    <T is={gltf.nodes.Hips} />
    <T.SkinnedMesh
      geometry={gltf.nodes.EyeLeft.geometry}
      material={gltf.materials.Wolf3D_Eye}
      skeleton={gltf.nodes.EyeLeft.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.EyeRight.geometry}
      material={gltf.materials.Wolf3D_Eye}
      skeleton={gltf.nodes.EyeRight.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Head.geometry}
      material={gltf.materials.Wolf3D_Skin}
      skeleton={gltf.nodes.Wolf3D_Head.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Teeth.geometry}
      material={gltf.materials.Wolf3D_Teeth}
      skeleton={gltf.nodes.Wolf3D_Teeth.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Hair.geometry}
      material={gltf.materials.Wolf3D_Hair}
      skeleton={gltf.nodes.Wolf3D_Hair.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Glasses.geometry}
      material={gltf.materials.Wolf3D_Glasses}
      skeleton={gltf.nodes.Wolf3D_Glasses.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Top.geometry}
      material={gltf.materials.Wolf3D_Outfit_Top}
      skeleton={gltf.nodes.Wolf3D_Outfit_Top.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Bottom.geometry}
      material={gltf.materials.Wolf3D_Outfit_Bottom}
      skeleton={gltf.nodes.Wolf3D_Outfit_Bottom.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Outfit_Footwear.geometry}
      material={gltf.materials.Wolf3D_Outfit_Footwear}
      skeleton={gltf.nodes.Wolf3D_Outfit_Footwear.skeleton}
    />
    <T.SkinnedMesh
      geometry={gltf.nodes.Wolf3D_Body.geometry}
      material={gltf.materials.Wolf3D_Body}
      skeleton={gltf.nodes.Wolf3D_Body.skeleton}
    />
  {:catch error}
    <slot name="error" {error} />
  {/await}

  <slot {ref} />
</T>
```

**Error:**
![image](https://github.com/threlte/threlte/assets/22219315/5927c064-b03f-4387-a783-e1dc43e92eab)

**Error in console**
![image](https://github.com/threlte/threlte/assets/22219315/7fa0c01b-2774-4349-aa0f-909c3d1ee457)

**I'm using** 
- Windows 10
- VSCode v1.89
- `"@threlte/core": "^7.3.0"`
- `"@threlte/extras": "^8.11.2"`
- `"three": "^0.165.0"`
- `"svelte": "^3.59.2",`
- `"svelte-preprocess": "^5.1.3",`

**Comment by DefinitelyMaybe** [comment]
Hey, quick query about the search params, how did you get to `?morphTargets=Oculus Visemes` ? I threw together a new URLSearchParams object and it came up as `?morphTargets=Oculus+Visemes`

**Comment by adamhemzal** [comment]
@DefinitelyMaybe thank you for the quick reply. I tried `?morphTargets=Oculus+Visemes` but still had the same issue. I also tried changing the empty space to `?morphTargets=Oculus%20Visemes`, but nothing has changed.

There is documentation for [GET - 3D Avatar](https://docs.readyplayer.me/ready-player-me/api-reference/rest-api/avatars/get-3d-avatars#query-parameters). If you scroll down to `?morphTargets` and click on the examples, you can see that there is a recommended search parameter (check the picture below). I'm just following documentation.

**I also made the same project in `react` using `@react-three/fiber` and it works fine with the space `Oculus Visemes` - I get avatar and `morphTargets`.  I think there must be some kind of issue in parsing URL in `useGltf()` hook but I don't know exactly.**

![image](https://github.com/threlte/threlte/assets/22219315/0f2066fd-0bfa-41af-b0c1-944db7fc6f3c)

**Comment by adamhemzal** [comment]
@DefinitelyMaybe I've debugged the code and found a solution. 

If `morphTargets` are present, Threlte tries to loop through all `SkinnedMesh` objects and find `morphTargetInfluences`. However, if you don't define `morphTargets` in your `SkinnedMesh`, it won't show up and will cause an error.

The solution is to define `morphTargets` for all your `SkinnedMesh` objects.

```javascript
      <T.SkinnedMesh
        name="Wolf3D_Head"
        geometry={gltf.nodes.Wolf3D_Head.geometry}
        material={gltf.materials.Wolf3D_Skin}
        skeleton={gltf.nodes.Wolf3D_Head.skeleton}
        morphTargetInfluences={gltf.nodes.Wolf3D_Head.morphTargetInfluences} // 👈 added manually
        morphTargetDictionary={gltf.nodes.Wolf3D_Head.morphTargetDictionary} // 👈 added manually
      />
```

**Comment by DefinitelyMaybe** [comment]
TIL! good stuff @adamhemzal 👍
