### ISSUE TITLE
[next] Domain-specific contexts

### ISSUE THREAD

**Issue by grischaerbe** [threlte/threlte#998]
Currently, Threlte uses two contexts, one of which is part of the public API.

In an effort to support advanced patterns like `<HUD>` or `useViewport` we want to separate these two contexts to a multitude of contexts which can be created at any point in the component tree. We're therefore opting for domain-specific contexts:

- Scene Context
	- scene
- Camera Context
	- camera
- Renderer Context
	- colorSpace
	- toneMapping
	- dpr
	- shadows
	- colorManagementEnabled
	- useLegacyLights
	- renderer
- Scheduler Context
	- scheduler
	- renderMode
	- autoRender
	- frameInvalidated
	- advance
	- autoInvalidations
	- resetFrameInvalidation
	- mainStage
	- renderStage
	- autoRenderTask
	- shouldRender
- Disposal Context
	- dispose
	- collectDisposableObjects
	- addDisposableObjects
	- removeDisposableObjects
	- disposableObjects
	- shouldDispose
- Cache Context
	- remember
	- clear
- (Plugins Context)
	- plugins

Every context has at least two methods:

- `createXContext` to create the context
  - `(args) => ContextType`
- `useX` to use the context
  - `() => ContextType`

On top of that, there will be convenience functions that create *all* contexts at once:

- `createThrelteContext`

This PR intentionally leaves out the size management that Threlte currently does as it will not be used in Threlte 8.

**Comment by grischaerbe** [comment]
The current prototype uses these contexts:

```ts
type CacheContext = {
  items: Cache
  remember: <T>(callback: () => Promise<T>, keys: Keys) => Promise<T>
  clear: (keys: Keys) => void
}

type CameraContext = {
  camera: CurrentWritable<Camera>
}

type CanvasContext = {
  canvas: HTMLCanvasElement
  size: Readable<Size>
}

type DisposalContext = {
  dispose: (force?: boolean) => void
  collectDisposableObjects: (
    object?: DisposableThreeObject,
    arr?: DisposableThreeObject[]
  ) => DisposableThreeObject[]
  addDisposableObjects: (objects: DisposableThreeObject[]) => void
  removeDisposableObjects: (objects: DisposableThreeObject[]) => void
  disposableObjects: Map<DisposableThreeObject, number>
  shouldDispose: boolean
}

type RendererContext = {
  renderer: Renderer
  colorManagementEnabled: CurrentWritable<boolean>
  colorSpace: CurrentWritable<ColorSpace>
  toneMapping: CurrentWritable<ToneMapping>
  shadows: CurrentWritable<boolean | ShadowMapType>
  dpr: CurrentWritable<number>
  autoRenderTask: Task
}

type SceneContext = {
  scene: Scene
}

type SchedulerContext = {
  scheduler: Scheduler
  renderMode: CurrentWritable<'always' | 'on-demand' | 'manual'>
  autoRender: CurrentWritable<boolean>
  frameInvalidated: boolean
  advance: () => void
  shouldAdvance: boolean
  autoInvalidations: Set<unknown>
  resetFrameInvalidation: () => void
  shouldRender: () => boolean
  invalidate: () => void
  mainStage: Stage
  renderStage: Stage
}
```

I'm thinking about separating out the `RenderContext` which would hold properties that currently belong to the `RendererContext`, such as the `autoRenderTask` and properties that are part of the `SchedulerStage` such as the `renderMode`. Does that make sense? I'm not sure about a clear separation here, what do you think @michealparks? The rest feels pretty solid 👍

**Comment by michealparks** [comment]
Yeah, from a first glance it feels like `autoRenderTask` should be in `SchedulerContext`, aside from that everything looks like it's in the right place

**Comment by grischaerbe** [comment]
The reason for a `RenderContext` (=!= `RendererContext`!) would be to eliminate the conceptual overlap of `SchedulerContext` and `RenderContext`.

**Comment by michealparks** [comment]
Ah ok! I see what you mean. What's the difference between RenderContext and SchedulerContext? I'm not sure if I can tell the difference.
